(() => {
  const APK_URL='https://github.com/Brett81Ross/cactusbyte-studios/releases/download/android-latest/ShadowNex-Prime.apk';
  const APP_NAME='ShadowNex Prime';
  const native=()=>/CactusByteNative\/1\.0/i.test(navigator.userAgent),ios=()=>/iPhone|iPad|iPod/i.test(navigator.userAgent);
  window.addEventListener('beforeinstallprompt',e=>e.preventDefault());
  function notice(m){let t=document.getElementById('cactusbyte-native-install-toast');if(!t){t=document.createElement('div');t.id='cactusbyte-native-install-toast';Object.assign(t.style,{position:'fixed',left:'50%',bottom:'70px',transform:'translateX(-50%)',zIndex:'2147483647',maxWidth:'min(92vw,420px)',padding:'10px 14px',borderRadius:'999px',background:'#07090d',border:'1px solid rgba(86,240,231,.52)',color:'#f4fffe',font:'700 12px/1.35 system-ui,sans-serif',boxShadow:'0 12px 32px rgba(0,0,0,.5)',textAlign:'center'});document.body.appendChild(t)}t.textContent=m;t.hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>t.hidden=true,3200)}
  function install(){if(native())return notice(`${APP_NAME} is already running as the installed Android app.`);if(ios())return notice('Native iPhone/iPad installation will use TestFlight or the App Store — no browser shortcut.');notice(`Downloading the real ${APP_NAME} Android app…`);window.location.assign(APK_URL)}
  document.addEventListener('click',e=>{const t=e.target instanceof Element?e.target.closest('button,a'):null;if(!t)return;const label=(t.textContent||'').trim().replace(/\s+/g,' ');if(!/^(?:⬇\s*)?(?:install(?: app)?|android install|download for android)$/i.test(label))return;e.preventDefault();e.stopImmediatePropagation();install()},true);
  function mount(){const existing=[...document.querySelectorAll('button,a')].find(el=>/^(?:⬇\s*)?(?:install(?: app)?|android install|download for android)$/i.test((el.textContent||'').trim().replace(/\s+/g,' ')));if(existing){existing.hidden=false;existing.removeAttribute('hidden');return}const b=document.createElement('button');b.type='button';b.textContent='⬇ INSTALL APP';b.className='hud-btn';Object.assign(b.style,{position:'fixed',left:'14px',bottom:'14px',zIndex:'2147483000',minHeight:'42px',boxShadow:'0 8px 24px rgba(0,0,0,.38)'});b.addEventListener('click',install);document.body.appendChild(b)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
