import { escapeHtml, fmtAlt, fmtNum } from '../core/geo.js';
import { correlateContacts } from '../core/contactCorrelation.js';

export function installAblEnhancements(app){
  app.lowPower=false;app.pressureHits=0;app.recoveryHits=0;
  const originalInit=app.init.bind(app),originalBind=app.bindUi.bind(app),originalDensity=app.densityLimit.bind(app),originalStability=app.handleStability.bind(app),originalDiagnostics=app.updateDiagnostics.bind(app);

  app.init=async function(){
    const result=await originalInit();
    this.performanceTimer=setInterval(()=>this.watchPerformance(),4000);
    this.renderStatusStrip();
    return result;
  };
  app.bindUi=function(){
    originalBind();
    this.$('homeBtn').onclick=()=>this.resetView();
  };
  app.densityLimit=function(low,normal,high){return this.lowPower?Math.max(40,Math.floor(low*.75)):originalDensity(low,normal,high);};
  app.renderPulse=function(){
    const all=this.registry.all();this.$('pulseSummary').textContent=this.registry.summary();this.$('pulseGrid').innerHTML=all.map(x=>`<div class="pulse-card"><b>${escapeHtml(x.label)}</b><span class="status-${x.status.toLowerCase()}">${x.status}</span><small>${x.count?` · ${x.count}`:''}</small></div>`).join('');this.renderStatusStrip();
  };
  app.resetView=function(){this.globe.sceneDirector?.stop(false);this.globe.cancelAnnotation();this.globe.clearSelection();this.setLens('normal');this.globe.home(true);this.$('layerPanel').classList.remove('open');this.toast('Returned to the full-Earth home view.');};
  app.renderStatusStrip=function(){if(!this.$||!this.globe)return;const map=this.globe.baseMapInfo?.()||{status:'READY'};const a=this.registry.get('aircraft'),q=this.registry.get('earthquakes');this.$('mapStatusMap').textContent=map.status==='READY'?'EARTH READY':map.status==='FALLBACK'?'EARTH FALLBACK':'EARTH LOADING';this.$('mapStatusAircraft').textContent=`AIRCRAFT ${a?.status||'STARTING'}`;this.$('mapStatusQuakes').textContent=`QUAKES ${q?.status||'STARTING'}`;this.$('performanceBadge').classList.toggle('hidden',!this.lowPower);};
  app.setLowPower=function(on,reason=''){if(this.lowPower===!!on)return;this.lowPower=!!on;document.getElementById('app').classList.toggle('low-power',this.lowPower);if(this.globe?.viewer)this.globe.viewer.resolutionScale=this.lowPower?(this.compact?.6:.82):(this.compact?.72:1);this.layers.get('aircraft')?.applyPerformanceMode?.(this.lowPower);this.layers.get('satellites')?.applyPerformanceMode?.(this.lowPower);this.renderStatusStrip();this.updateDiagnostics();this.toast(this.lowPower?`Low-power map mode enabled${reason?` · ${reason}`:''}.`:'Full map detail restored.');};
  app.watchPerformance=function(){const count=this.globe?.viewer?.entities?.values?.length||0,threshold=this.compact?520:1400;if(count>threshold){this.pressureHits++;this.recoveryHits=0;}else{this.pressureHits=0;if(this.lowPower&&count<threshold*.55)this.recoveryHits++;else this.recoveryHits=0;}if(!this.lowPower&&this.pressureHits>=2)this.setLowPower(true,'high map load');if(this.lowPower&&this.recoveryHits>=4)this.setLowPower(false,'load recovered');};
  app.handleStability=function(detail={}){if(detail.state==='lost'||detail.state==='warning')this.setLowPower(true,'graphics recovery');originalStability(detail);this.renderStatusStrip();};
  app.updateDiagnostics=function(){originalDiagnostics();if(!this.$)return;const d=this.$('diagnostics');d.insertAdjacentHTML('beforeend',`<span>Earth basemap: ${escapeHtml(this.globe?.baseMapInfo?.().name||'CHECKING')}</span><span>Performance: ${this.lowPower?'LOW POWER':'NORMAL'}</span>`);};
  app.contactValue=function(k,v){if(k==='altitude')return fmtAlt(Number(v));if(k==='velocity'&&Number.isFinite(Number(v)))return `${Math.round(Number(v)*1.94384)} kt`;if(typeof v==='number')return fmtNum(v,2);return String(v);};
  app.primaryContactRows=function(m){const out=[];const add=(k,v)=>{if(v!=null&&v!==''&&out.length<3)out.push([k,String(v)]);};if(m.type==='AIRCRAFT'){add('Altitude',Number.isFinite(Number(m.altitude))?fmtAlt(Number(m.altitude)):null);add('Speed',Number.isFinite(Number(m.velocity))?`${Math.round(Number(m.velocity)*1.94384)} kt`:null);add('Source',m.source);}else if(m.type==='EARTHQUAKE'){add('Magnitude',Number.isFinite(Number(m.magnitude))?`M${Number(m.magnitude).toFixed(1)}`:null);add('Depth',Number.isFinite(Number(m.depthKm))?`${Number(m.depthKm).toFixed(1)} km`:null);add('Source',m.source);}else if(m.type==='VESSEL'){add('Speed',Number.isFinite(Number(m.speed))?`${Number(m.speed).toFixed(1)} kt`:null);add('Heading',Number.isFinite(Number(m.heading))?`${Math.round(Number(m.heading))}°`:null);add('Source',m.source);}else if(m.type==='SATELLITE'){add('Altitude',Number.isFinite(Number(m.altitude))?fmtAlt(Number(m.altitude)):null);add('Position','ESTIMATED');add('Source',m.source);}else if(m.type==='LAUNCH'){add('Status',m.status);add('When',m.net);add('Source',m.source);}else{add('Type',m.type);add('Source',m.source);add('Status',m.status);}return out;};
  app.humanSummary=function(m){const name=String(m.name||m.type||'This contact');if(m.type==='AIRCRAFT'){const alt=Number(m.altitude),spd=Number(m.velocity),hdg=Number(m.heading);if(m.onGround)return `${name} is reported on the ground by ${m.source||'the public source'}.`;let s=`${name} is airborne`;if(Number.isFinite(alt))s+=` at ${fmtAlt(alt)}`;if(Number.isFinite(spd))s+=`, moving at about ${Math.round(spd*1.94384)} kt`;if(Number.isFinite(hdg))s+=` on heading ${Math.round((hdg%360+360)%360)}°`;return s+'.';}if(m.type==='EARTHQUAKE'){const mag=Number(m.magnitude),depth=Number(m.depthKm);return `${Number.isFinite(mag)?`Magnitude ${mag.toFixed(1)} earthquake`:'Earthquake'} near ${name}${Number.isFinite(depth)?` at ${depth.toFixed(1)} km depth`:''}.`;}if(m.type==='FIRE')return `${name} is an active wildfire report from ${m.source||'a public NASA source'}.`;if(m.type==='SATELLITE')return `${name} is shown at an estimated orbital position calculated from public CelesTrak TLE data.`;if(m.type==='VESSEL'){const spd=Number(m.speed);return `${name} is a live AIS vessel contact${Number.isFinite(spd)?` moving at ${spd.toFixed(1)} kt`:''}.`;}if(m.type==='LAUNCH')return `${name} is a launch event from Launch Library 2${m.status?` with status ${m.status}`:''}.`;if(m.type==='CCTV')return `${name} is a public traffic-camera location from ${m.source||'the listed source'}.`;return `${name} is a ${String(m.type||'contact').toLowerCase()} from ${m.source||'a public source'}.`;};
  app.renderScope=function(meta){
    const empty=this.$('scopeEmpty'),box=this.$('scopeContent'),actions=this.$('scopeActions'),close=this.$('scopeCloseBtn'),panel=this.$('scopePanel');if(!meta){empty.classList.remove('hidden');box.classList.add('hidden');actions.classList.add('hidden');close.classList.add('hidden');panel.classList.remove('expanded');return;}empty.classList.add('hidden');box.classList.remove('hidden');actions.classList.remove('hidden');close.classList.remove('hidden');if(this.compact)panel.classList.add('expanded');
    const primary=this.primaryContactRows(meta).map(([k,v])=>`<div class="scope-row primary"><span>${escapeHtml(k)}</span><span>${escapeHtml(v)}</span></div>`).join('');const rows=[];const skip=new Set(['name','type','url','stream']);for(const [k,v] of Object.entries(meta)){if(skip.has(k)||v==null||v==='')continue;rows.push(`<div class="scope-row"><span>${escapeHtml(k.replace(/[A-Z]/g,m=>' '+m).toUpperCase())}</span><span>${escapeHtml(this.contactValue(k,v))}</span></div>`);}box.innerHTML=`<div class="scope-name">${escapeHtml(meta.name||meta.type||'CONTACT')}</div><p class="contact-summary">${escapeHtml(this.humanSummary(meta))}</p><div class="primary-metrics">${primary}</div><details class="technical-data"><summary>MORE DETAILS</summary>${rows.join('')}</details>`;
    if(meta.type==='RADIO'&&meta.stream){const play=document.createElement('button');play.className='hud-btn wide';play.textContent='PLAY RADIO';play.onclick=()=>{this.audio.src=meta.stream;this.audio.play().then(()=>this.toast(`Playing ${meta.name}`)).catch(()=>this.toast('Radio stream could not be played.'));};box.appendChild(play);}if(meta.url){const open=document.createElement('button');open.className='ghost-btn wide';open.textContent='OPEN SOURCE';open.onclick=()=>window.open(meta.url,'_blank','noopener');box.appendChild(open);}if(meta.type==='LAUNCH'){const recon=document.createElement('button');recon.className='hud-btn wide';recon.textContent='RECONSTRUCT LAUNCH';recon.onclick=e=>{e.stopPropagation();this.globe.sceneDirector.launchReconstruction(meta);};box.appendChild(recon);}const nearby=correlateContacts(meta,[...this.layers.values()],{radiusKm:250,limit:8});if(nearby.length){const wrap=document.createElement('div');wrap.className='correlation-box';const title=document.createElement('b');title.textContent=`NEARBY CONTACTS · ${nearby.length}`;wrap.appendChild(title);for(const x of nearby){const row=document.createElement('button');row.className='correlation-row';row.innerHTML=`<div><strong>${escapeHtml(x.meta.name||x.meta.type||'CONTACT')}</strong><small>${escapeHtml(x.relation)} · ${escapeHtml(x.meta.type||'CONTACT')}</small></div><span>${x.distanceKm.toFixed(1)} KM</span>`;row.onclick=e=>{e.stopPropagation();this.globe.select(x.meta,x.entity);if(Number.isFinite(x.meta.longitude)&&Number.isFinite(x.meta.latitude))this.globe.flyTo(x.meta.longitude,x.meta.latitude,Math.max(120000,Number(x.meta.altitude)||250000));};wrap.appendChild(row);}box.appendChild(wrap);}
  };
}
