import { escapeHtml } from '../core/geo.js';

const PRESETS={
  overview:{label:'Global Overview',layers:['aircraft','earthquakes','fires'],message:'A lightweight world view of aircraft, earthquakes, and active fires.'},
  emergency:{label:'Disaster & Emergency',layers:['earthquakes','fires','cctv'],message:'Focuses on earthquakes, active fires, and public cameras where available.'},
  aviation:{label:'Aviation & Maritime',layers:['aircraft','vessels'],message:'Focuses on live aircraft and AIS vessels when an AISStream key is available.'},
  space:{label:'Space & Exploration',layers:['satellites','launches','subsea'],message:'Shows satellite estimates, launches, and mapped subsea infrastructure.'},
  infrastructure:{label:'Infrastructure',layers:['context','subsea','cctv'],message:'Shows mapped infrastructure, subsea cables, and public cameras where available.'}
};

export function installIntelligenceEnhancements(app){
  app.activeMode='overview';app.recoveryWatch=new Map();app.recoveryCooldown=new Map();
  const originalInit=app.init.bind(app),originalBind=app.bindUi.bind(app),originalRenderScope=app.renderScope.bind(app);

  app.init=async function(){const result=await originalInit();this.startRecoveryWatchdog();return result;};
  app.bindUi=function(){
    originalBind();
    this.ensureIntelligenceUi();
    this.$('searchBtn').onclick=()=>this.openSearch();
    this.$('modesBtn').onclick=()=>this.openModes();
    this.$('searchRunBtn').onclick=()=>this.runUniversalSearch();
    this.$('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();this.runUniversalSearch();}});
    document.querySelectorAll('[data-search-example]').forEach(b=>b.onclick=()=>{this.$('searchInput').value=b.dataset.searchExample;this.runUniversalSearch();});
    document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>this.applyPreset(b.dataset.preset));
    this.$('advancedModeBtn').onclick=()=>{this.$('modesDialog').close();this.$('layerPanel').classList.add('open');document.querySelector('.advanced-tools')?.setAttribute('open','');this.toast('Advanced controls opened.');};
  };

  app.ensureIntelligenceUi=function(){
    if(!document.querySelector('link[href="/src/ui/intelligence.css"]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/src/ui/intelligence.css';document.head.appendChild(link);}
    const top=document.querySelector('.top-actions');if(top&&!this.$('searchBtn')){const search=document.createElement('button');search.id='searchBtn';search.className='hud-btn';search.textContent='SEARCH';const modes=document.createElement('button');modes.id='modesBtn';modes.className='hud-btn';modes.textContent='MODES';const command=this.$('commandBtn');top.insertBefore(search,command);top.insertBefore(modes,command);}
    if(!this.$('searchDialog')){const host=document.getElementById('app');host.insertAdjacentHTML('beforeend',`<dialog id="searchDialog" class="modal glass"><div class="modal-card command-card"><div class="modal-head"><div><b>Search ShadowNex</b><small>PLACE · CALLSIGN · SATELLITE · VESSEL · COORDINATES</small></div><button id="searchCloseBtn" class="icon-btn" type="button">✕</button></div><div class="search-input-row"><input id="searchInput" placeholder="Search anywhere or any active contact…" autocomplete="off" /><button id="searchRunBtn" type="button" class="hud-btn">SEARCH</button></div><div class="search-examples"><button type="button" data-search-example="Oklahoma City">Oklahoma City</button><button type="button" data-search-example="Tokyo">Tokyo</button><button type="button" data-search-example="35.4676, -97.5164">Coordinates</button></div><div id="searchResults" class="search-results"><div class="search-hint">Search a place, callsign, satellite, vessel, landmark, or coordinates.</div></div></div></dialog><dialog id="modesDialog" class="modal glass"><div class="modal-card"><div class="modal-head"><div><b>Choose What You Want to See</b><small>GUIDED MODES · YOU CAN STILL CHANGE LAYERS LATER</small></div><button id="modesCloseBtn" class="icon-btn" type="button">✕</button></div><div class="preset-grid"><button class="preset-card active" type="button" data-preset="overview"><strong>Global Overview</strong><small>Aircraft, earthquakes, and active fires without turning everything on.</small></button><button class="preset-card" type="button" data-preset="emergency"><strong>Disaster & Emergency</strong><small>Earthquakes, fires, and public cameras where available.</small></button><button class="preset-card" type="button" data-preset="aviation"><strong>Aviation & Maritime</strong><small>Aircraft plus live AIS vessels when your key is configured.</small></button><button class="preset-card" type="button" data-preset="space"><strong>Space & Exploration</strong><small>Satellites, launches, and mapped subsea infrastructure.</small></button><button class="preset-card" type="button" data-preset="infrastructure"><strong>Infrastructure</strong><small>Mapped infrastructure, subsea cables, and public cameras.</small></button><button id="advancedModeBtn" class="preset-card" type="button"><strong>Custom / Advanced</strong><small>Open the full layer list and advanced tools without changing your current view.</small></button></div></div></dialog>`);}
    this.$('searchCloseBtn').onclick=()=>this.$('searchDialog').close();this.$('modesCloseBtn').onclick=()=>this.$('modesDialog').close();
  };

  app.openSearch=function(){const d=this.$('searchDialog');this.$('searchResults').innerHTML='<div class="search-hint">Search a place, callsign, satellite, vessel, landmark, or coordinates.</div>';if(!d.open)d.showModal();setTimeout(()=>this.$('searchInput').focus(),50);};
  app.openModes=function(){const d=this.$('modesDialog');if(!d.open)d.showModal();};
  app.contactMeta=function(entity){try{return entity?.properties?.snxMeta?.getValue?.(this.globe.viewer.clock.currentTime)??entity?.snxMeta??null}catch{return null}};
  app.searchActiveContacts=function(query){const q=query.trim().toLowerCase(),out=[],seen=new Set();if(!q)return out;for(const layer of this.layers.values()){for(const entity of layer.entities||[]){const m=this.contactMeta(entity);if(!m||m.type==='CLUSTER')continue;const id=String(m.id||''),name=String(m.name||''),type=String(m.type||''),hay=`${name} ${id} ${type}`.toLowerCase();if(!hay.includes(q))continue;const key=`${type}:${id||name}`;if(seen.has(key))continue;seen.add(key);let score=4;if(name.toLowerCase()===q||id.toLowerCase()===q)score=0;else if(name.toLowerCase().startsWith(q)||id.toLowerCase().startsWith(q))score=1;else if(type.toLowerCase()===q)score=2;out.push({meta:m,entity,score});}}return out.sort((a,b)=>a.score-b.score||String(a.meta.name||'').localeCompare(String(b.meta.name||''))).slice(0,8);};
  app.selectSearchHit=function(hit){this.globe.select(hit.meta,hit.entity);const lon=Number(hit.meta.longitude),lat=Number(hit.meta.latitude);if(Number.isFinite(lon)&&Number.isFinite(lat))this.globe.flyTo(lon,lat,Math.max(180000,Number(hit.meta.altitude)||500000));this.$('searchDialog').close();};
  app.runUniversalSearch=async function(){
    const input=this.$('searchInput'),raw=input.value.trim(),results=this.$('searchResults');if(!raw)return;
    results.innerHTML='<div class="search-hint busy">Searching ShadowNex…</div>';
    const coord=raw.match(/^\s*(-?\d+(?:\.\d+)?)\s*[, ]\s*(-?\d+(?:\.\d+)?)\s*$/);if(coord){const lat=Number(coord[1]),lon=Number(coord[2]);if(lat>=-90&&lat<=90&&lon>=-180&&lon<=180){this.globe.flyTo(lon,lat,700000);results.innerHTML=`<button class="search-result"><strong>${lat.toFixed(4)}, ${lon.toFixed(4)}</strong><small>Coordinates · map centered</small></button>`;setTimeout(()=>this.$('searchDialog').close(),250);return;}}
    const hits=this.searchActiveContacts(raw);results.innerHTML='';
    for(const hit of hits){const b=document.createElement('button');b.className='search-result';b.innerHTML=`<strong>${escapeHtml(hit.meta.name||hit.meta.id||hit.meta.type)}</strong><small>${escapeHtml(hit.meta.type||'CONTACT')} · ${escapeHtml(hit.meta.source||'active feed')}</small>`;b.onclick=()=>this.selectSearchHit(hit);results.appendChild(b);}
    try{const r=await fetch(`/api/boundary?q=${encodeURIComponent(raw)}`);const d=await r.json();if(r.ok&&Array.isArray(d.bbox)&&d.bbox.length===4){const [west,south,east,north]=d.bbox.map(Number),lon=(west+east)/2,lat=(south+north)/2,span=Math.max(Math.abs(east-west),Math.abs(north-south));const b=document.createElement('button');b.className='search-result place';b.innerHTML=`<strong>${escapeHtml(d.name||raw)}</strong><small>Place / landmark · OpenStreetMap</small>`;b.onclick=()=>{this.globe.flyTo(lon,lat,Math.max(250000,span*150000));this.$('searchDialog').close();};results.appendChild(b);}}catch{}
    if(!results.children.length)results.innerHTML='<div class="search-hint">No match in active feeds or place search. Try turning on the relevant mode first.</div>';
  };

  app.applyPreset=async function(id){const preset=PRESETS[id];if(!preset)return;this.activeMode=id;this.$('modesDialog').close();this.toast(`Loading ${preset.label}…`);const keep=new Set(preset.layers);for(const layer of this.layers.values()){if(layer.enabled&&!keep.has(layer.id))layer.disable();}if(this.globe.trafficLayer&&!keep.has('traffic'))await this.setLayer('traffic',false);for(const layerId of preset.layers){if(layerId==='vessels'&&!this.settings.aisKey){this.registry.set('vessels',{status:'STANDBY',note:'AISStream key required'});continue;}await this.setLayer(layerId,true);}document.querySelectorAll('[data-preset]').forEach(b=>b.classList.toggle('active',b.dataset.preset===id));this.renderLayers();this.toast(`${preset.label} ready. ${preset.message}`);};

  app.startRecoveryWatchdog=function(){if(this.recoveryWatchTimer)return;this.recoveryWatchTimer=setInterval(()=>this.runRecoveryWatchdog(),15000);};
  app.runRecoveryWatchdog=function(){const now=Date.now();for(const layer of this.layers.values()){if(!layer.enabled||layer.id==='vessels')continue;const state=this.registry.get(layer.id);if(!state)continue;const staleLive=state.status==='LIVE'&&state.updatedAt&&now-state.updatedAt>Math.max(180000,(layer.interval||60000)*4);const unhealthy=['DEGRADED','STALE'].includes(state.status)||staleLive;const hits=unhealthy?(this.recoveryWatch.get(layer.id)||0)+1:0;this.recoveryWatch.set(layer.id,hits);if(hits<3)continue;const last=this.recoveryCooldown.get(layer.id)||0;if(now-last<300000)continue;this.recoveryCooldown.set(layer.id,now);this.recoveryWatch.set(layer.id,0);this.recoverLayer(layer,staleLive?'feed stalled':state.status.toLowerCase());}};
  app.recoverLayer=async function(layer,reason){if(!layer?.enabled)return;this.registry.set(layer.id,{status:'SYNC',note:`Automatic recovery · ${reason}`});try{if(layer.timer)clearTimeout(layer.timer);layer.timer=null;layer.refreshing=false;await layer.cycle?.(layer.generation);this.toast(`${layer.label} feed recovered.`);}catch(e){console.warn('[watchdog]',layer.id,e);}};

  app.confidenceInfo=function(meta){const type=String(meta.type||'').toUpperCase(),layerMap={AIRCRAFT:'aircraft',VESSEL:'vessels',SATELLITE:'satellites',LAUNCH:'launches',EARTHQUAKE:'earthquakes',FIRE:'fires',CCTV:'cctv',RADIO:'radio',BIKE:'bikeshare',MILITARY_SITE:'context',INFRASTRUCTURE:'context'},sourceState=this.registry.get(layerMap[type]);let status='REPORTED',quality='PUBLIC SOURCE';if(type==='AIRCRAFT'){status=meta.militaryLikely?'INFERRED':'LIVE';quality=meta.militaryLikely?'PUBLIC ADS-B · MILITARY-LIKELY IS HEURISTIC':'PUBLIC ADS-B';}else if(type==='VESSEL'){status='LIVE';quality='PUBLIC AIS';}else if(type==='SATELLITE'){status='ESTIMATED';quality='TLE PROPAGATION';}else if(type==='CLUSTER'){status='AGGREGATED';quality='SHADOWNEX MAP AGGREGATION';}else if(type==='LAUNCH'){status='REPORTED';quality='SCHEDULE / EVENT DATA';}else if(type==='EARTHQUAKE')quality='USGS EVENT FEED';else if(type==='FIRE')quality='NASA EVENT / DETECTION FEED';if(sourceState&&['STALE','DEGRADED','UNAVAILABLE'].includes(sourceState.status))status='STALE';const updatedAt=Number(meta.updatedAt||sourceState?.updatedAt)||null;return {status,quality,source:meta.source||sourceState?.provenance||'Public source',updatedAt};};
  app.formatAge=function(ts){if(!ts)return 'update time unavailable';const sec=Math.max(0,Math.round((Date.now()-ts)/1000));if(sec<60)return `${sec}s ago`;const min=Math.round(sec/60);if(min<60)return `${min}m ago`;const hr=Math.round(min/60);return `${hr}h ago`;};
  app.renderScope=function(meta){originalRenderScope(meta);if(!meta)return;const box=this.$('scopeContent'),summary=box.querySelector('.contact-summary');if(!summary)return;const info=this.confidenceInfo(meta),wrap=document.createElement('div');wrap.className='provenance-strip';wrap.innerHTML=`<div class="confidence-badge ${info.status.toLowerCase()}">${escapeHtml(info.status)}</div><div><strong>${escapeHtml(info.source)}</strong><small>${escapeHtml(this.formatAge(info.updatedAt))} · ${escapeHtml(info.quality)}</small></div>`;summary.insertAdjacentElement('afterend',wrap);};
}
