import { escapeHtml } from '../core/geo.js';
export function installProfileEnhancements(app){
  app.profileToken=0;const original=app.renderScope.bind(app);
  app.renderScope=function(meta){original(meta);this.renderRichProfile(meta);};
  app.renderRichProfile=async function(meta){const box=this.$?.('scopeContent');if(!box)return;box.querySelector('.rich-profile')?.remove();if(!meta)return;const token=++this.profileToken,kind=String(meta.type||'').toUpperCase(),holder=document.createElement('section');holder.className='rich-profile';box.appendChild(holder);if(kind==='CCTV'){holder.innerHTML=this.cameraProfileHtml(meta);return;}if(!['AIRCRAFT','SATELLITE'].includes(kind)){holder.remove();return;}holder.innerHTML='<div class="profile-loading">Loading public profile…</div>';const q=new URLSearchParams({type:kind.toLowerCase(),id:String(meta.id||''),name:String(meta.name||''),callsign:String(meta.name||'')});try{const r=await fetch(`/api/enrich?${q}`),d=await r.json();if(token!==this.profileToken||!box.isConnected)return;if(!d?.available){holder.innerHTML='<div class="profile-empty">No additional public profile is available for this subject yet.</div>';return;}holder.innerHTML=kind==='AIRCRAFT'?this.aircraftProfileHtml(meta,d):this.satelliteProfileHtml(meta,d);const source=holder.querySelector('.profile-source');if(source&&d.url)source.onclick=()=>window.open(d.url,'_blank','noopener');}catch{if(token===this.profileToken)holder.innerHTML='<div class="profile-empty">Extra public details are temporarily unavailable.</div>';}};app.mediaHtml=function(url,alt){return url?`<img class="profile-photo" src="${escapeHtml(url)}" alt="${escapeHtml(alt)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.remove()" />`:'';};
  app.aircraftProfileHtml=function(meta,d){const a=d.aircraft||{},r=d.route||{},o=r.origin||{},dest=r.destination||{},route=o.icao||dest.icao?`${o.name||o.icao||'Unknown origin'} → ${dest.name||dest.icao||'Unknown destination'}`:null;return `<div class="profile-title">AIRCRAFT PROFILE <small>PUBLIC REFERENCE DATA</small></div>${this.mediaHtml(d.photoThumbnail||d.photo,`${meta.name||'Aircraft'} photo`)}<div class="profile-grid">${a.registration?`<div><span>REGISTRATION</span><b>${escapeHtml(a.registration)}</b></div>`:''}${a.manufacturer||a.type?`<div><span>AIRCRAFT</span><b>${escapeHtml([a.manufacturer,a.type].filter(Boolean).join(' '))}</b></div>`:''}${a.owner?`<div><span>REGISTERED OWNER</span><b>${escapeHtml(a.owner)}</b></div>`:''}${route?`<div class="wide"><span>PUBLISHED ROUTE MATCH</span><b>${escapeHtml(route)}</b><small>${escapeHtml([o.iata||o.icao,dest.iata||dest.icao].filter(Boolean).join(' → '))}</small></div>`:''}</div><div class="profile-purpose"><span>MISSION / PURPOSE</span><p>${escapeHtml(d.purpose||'Specific mission is not publicly identified.')}</p></div><div class="profile-caveat">A route lookup may describe the callsign’s published route and is not proof of the aircraft’s current mission or passengers.</div>`;};
  app.satelliteProfileHtml=function(meta,d){return `<div class="profile-title">SATELLITE PROFILE <small>ENGLISH REFERENCE</small></div>${this.mediaHtml(d.photoThumbnail||d.photo,`${d.title||meta.name||'Satellite'} image`)}${d.title?`<h4>${escapeHtml(d.title)}</h4>`:''}${d.description?`<div class="profile-description">${escapeHtml(d.description)}</div>`:''}<div class="profile-purpose"><span>MISSION / PURPOSE</span><p>${escapeHtml(d.summary||'No English mission summary is available from the public reference source.')}</p></div>${d.url?'<button class="ghost-btn wide profile-source" type="button">OPEN ENGLISH SOURCE</button>':''}`;};
  app.cameraProfileHtml=function(meta){return `<div class="profile-title">CAMERA DETAILS <small>${escapeHtml(meta.source||'PUBLIC SOURCE')}</small></div>${this.mediaHtml(meta.previewUrl,`${meta.name||'Traffic camera'} current image`)}<div class="profile-purpose"><span>COVERAGE</span><p>${escapeHtml([meta.route,meta.county,meta.district,meta.view].filter(Boolean).join(' · ')||'Published public traffic-camera location.')}</p></div>`;};
}
