import { escapeHtml, fmtDistanceKm } from '../core/geo.js';
export function installProfileEnhancements(app){
  app.profileToken=0;const original=app.renderScope.bind(app);
  app.renderScope=function(meta){original(meta);this.renderRichProfile(meta);};
  app.mediaHtml=function(url,alt){return url?`<img class='profile-photo' src='${escapeHtml(url)}' alt='${escapeHtml(alt)}' loading='lazy' referrerpolicy='no-referrer' onerror='this.remove()'>`:'';};
  app.renderRichProfile=async function(meta){
    const box=this.$?.('scopeContent');if(!box)return;box.querySelector('.rich-profile')?.remove();if(!meta)return;
    const kind=String(meta.type||'').toUpperCase(),holder=document.createElement('section');holder.className='rich-profile';
    const name=box.querySelector('.scope-name');if(name)name.insertAdjacentElement('afterend',holder);else box.prepend(holder);
    if(kind==='CCTV'){holder.innerHTML=this.cameraProfileHtml(meta);return;}if(kind==='LAUNCH'){holder.innerHTML=this.launchProfileHtml(meta);return;}if(kind==='EARTHQUAKE'){holder.innerHTML=this.quakeProfileHtml(meta);return;}if(kind==='FIRE'){holder.innerHTML=this.fireProfileHtml(meta);return;}if(kind==='VESSEL'){holder.innerHTML=this.vesselProfileHtml(meta);return;}
    if(!['AIRCRAFT','SATELLITE'].includes(kind)){holder.remove();return;}const token=++this.profileToken;holder.innerHTML=`<div class='profile-loading'>Loading public profile…</div>`;
    const q=new URLSearchParams({type:kind.toLowerCase(),id:String(meta.id||''),name:String(meta.name||''),callsign:String(meta.name||'')});
    try{const r=await fetch(`/api/enrich?${q}`),d=await r.json();if(token!==this.profileToken||!box.isConnected)return;if(!d?.available){holder.innerHTML=`<div class='profile-empty'>No additional public profile is available for this subject yet.</div>`;return;}holder.innerHTML=kind==='AIRCRAFT'?this.aircraftProfileHtml(meta,d):this.satelliteProfileHtml(meta,d);const source=holder.querySelector('.profile-source');if(source&&d.url)source.onclick=()=>window.open(d.url,'_blank','noopener');}catch{if(token===this.profileToken)holder.innerHTML=`<div class='profile-empty'>Extra public details are temporarily unavailable.</div>`;}
  };
  app.aircraftProfileHtml=function(meta,d){const a=d.aircraft||{},r=d.route||{},o=r.origin||{},dest=r.destination||{},aircraft=[a.manufacturer,a.type].filter(Boolean).join(' '),route=o.icao||dest.icao?`${o.name||o.icao||'Unknown origin'} → ${dest.name||dest.icao||'Unknown destination'}`:null,lead=aircraft?`${aircraft}${a.owner?` · ${a.owner}`:''}`:(meta.militaryLikely?'Military-likely callsign heuristic':'Public aircraft contact');return `<div class='profile-title'>AIRCRAFT PROFILE <small>PUBLIC REFERENCE DATA</small></div>${this.mediaHtml(d.photoThumbnail||d.photo,`${meta.name||'Aircraft'} photo`)}<p class='profile-lead'>${escapeHtml(lead)}</p><div class='profile-grid'>${cell('Registration',a.registration)}${cell('Aircraft',aircraft)}${cell('Registered owner',a.owner)}${route?`<div class='wide'><span>PUBLISHED ROUTE MATCH</span><b>${escapeHtml(route)}</b><small>${escapeHtml([o.iata||o.icao,dest.iata||dest.icao].filter(Boolean).join(' → '))}</small></div>`:''}</div><div class='profile-purpose'><span>MISSION / PURPOSE</span><p>${escapeHtml(d.purpose||'Specific mission/purpose is not publicly identified.')}</p></div><div class='profile-caveat'>A published callsign route is not proof of the aircraft’s current mission, cargo, crew, or passengers.</div>`;};
  app.satelliteProfileHtml=function(meta,d){return `<div class='profile-title'>SATELLITE PROFILE <small>ENGLISH PUBLIC REFERENCE</small></div>${this.mediaHtml(d.photoThumbnail||d.photo,`${d.title||meta.name||'Satellite'} image`)}${d.title?`<h4>${escapeHtml(d.title)}</h4>`:''}${d.description?`<p class='profile-lead'>${escapeHtml(d.description)}</p>`:''}<div class='profile-purpose'><span>MISSION / PURPOSE</span><p>${escapeHtml(d.summary||'No English mission summary is available from the public reference source.')}</p></div>${d.url?`<button class='ghost-btn wide profile-source' type='button'>OPEN ENGLISH SOURCE</button>`:''}`;};
  app.cameraProfileHtml=function(m){return `<div class='profile-title'>CAMERA DETAILS <small>${escapeHtml(m.source||'PUBLIC SOURCE')}</small></div>${this.mediaHtml(m.previewUrl,`${m.name||'Traffic camera'} current image`)}<p class='profile-lead'>${escapeHtml([m.route,m.county,m.district,m.view].filter(Boolean).join(' · ')||'Published public traffic-camera location.')}</p>${m.streamUrl?`<div class='profile-purpose'><span>LIVE CAMERA</span><p>The provider reports a public stream for this camera. Stream availability can change.</p></div>`:''}`;};
  app.launchProfileHtml=function(m){return `<div class='profile-title'>LAUNCH PROFILE <small>LAUNCH LIBRARY 2</small></div>${this.mediaHtml(m.image,`${m.name||'Launch'} image`)}<div class='profile-grid'>${cell('Rocket',m.rocket)}${cell('Provider',m.provider)}${cell('Launch site',m.location||m.pad)}${cell('Orbit',m.orbit)}${cell('Status',m.status)}${cell('Launch time',m.net?new Date(m.net).toLocaleString('en-US'):null)}</div><div class='profile-purpose'><span>MISSION / PURPOSE</span><p>${escapeHtml(m.missionDescription||m.missionType||'A detailed public mission description is not available in the loaded launch record.')}</p></div>`;};
  app.quakeProfileHtml=function(m){return `<div class='profile-title'>EARTHQUAKE PROFILE <small>USGS</small></div><div class='profile-grid'>${cell('Magnitude',Number.isFinite(Number(m.magnitude))?`M${Number(m.magnitude).toFixed(1)}`:null)}${cell('Depth',Number.isFinite(Number(m.depthKm))?fmtDistanceKm(Number(m.depthKm)):null)}${cell('Felt reports',m.felt)}${cell('Significance',m.significance)}${cell('Alert',m.alert)}${cell('Tsunami flag',m.tsunami?'Yes':'No')}</div><div class='profile-purpose'><span>WHAT THIS MEANS</span><p>USGS event data for this earthquake. Impact depends on magnitude, depth, distance, local geology, and building conditions.</p></div>`;};
  app.fireProfileHtml=function(m){return `<div class='profile-title'>FIRE PROFILE <small>${escapeHtml(m.source||'NASA')}</small></div><div class='profile-grid'>${cell('Reported / detected',m.when?new Date(m.when).toLocaleString('en-US'):null)}${cell('Brightness',Number.isFinite(Number(m.brightness))?String(m.brightness):null)}</div><div class='profile-purpose'><span>STATUS</span><p>This is a public wildfire event/detection. Size, containment, and evacuation status are not inferred when the source does not provide them.</p></div>`;};
  app.vesselProfileHtml=function(m){const route=m.destination?`Published AIS destination: ${m.destination}.`:'Destination/purpose is not available in the current AIS record.';return `<div class='profile-title'>VESSEL PROFILE <small>PUBLIC AIS</small></div><div class='profile-grid'>${cell('MMSI',m.id)}${cell('Speed',Number.isFinite(Number(m.speed))?`${Number(m.speed).toFixed(1)} kt`:null)}${cell('Heading',Number.isFinite(Number(m.heading))?`${Math.round(Number(m.heading))}°`:null)}${cell('Status',m.cohort)}</div><div class='profile-purpose'><span>ROUTE / PURPOSE</span><p>${escapeHtml(route)}</p></div>`;};
}
function cell(k,v){return v==null||v===''?'':`<div><span>${escapeHtml(k.toUpperCase())}</span><b>${escapeHtml(String(v))}</b></div>`;}