import { escapeHtml, haversineKm, fmtDistanceKm } from '../core/geo.js';
import { correlateContacts } from '../core/contactCorrelation.js';
import { loadCollection, saveCollection, makeId, compactMeta, withinWindow } from '../core/watchStore.js';

export function installSblWatch(app){
  const originalBind=app.bindUi.bind(app),originalInit=app.init.bind(app),originalRenderScope=app.renderScope.bind(app);
  const originalPreset=app.applyPreset?.bind(app),originalWorldIntent=app.runWorldIntent?.bind(app);
  app.navHistory=[];app.activityWindowHours=24;

  app.bindUi=function(){
    originalBind();this.ensureWatchUi();
    const watch=this.$('navLayers');if(watch){watch.textContent='WATCH';watch.onclick=()=>this.openWatchCenter('views');}
    this.$('watchCloseBtn').onclick=()=>this.$('watchDialog').close();
    this.$('saveViewBtn').onclick=()=>this.saveCurrentView();this.$('addWatchBtn').onclick=()=>this.addCurrentWatchArea();
    this.$('favoriteSelectedBtn').onclick=()=>this.favoriteSelected();this.$('clearActivityBtn').onclick=()=>this.clearRecentActivity();
    document.querySelectorAll('[data-watch-tab]').forEach(b=>b.onclick=()=>this.showWatchTab(b.dataset.watchTab));
    document.querySelectorAll('[data-window-hours]').forEach(b=>b.onclick=()=>this.setActivityWindow(Number(b.dataset.windowHours)));
    this.$('moreLayersBtn').onclick=()=>{this.$('moreDialog').close();this.$('layerPanel').classList.add('open');};
    this.$('moreBackBtn').onclick=()=>{this.$('moreDialog').close();this.goBackState();};
    this.$('moreResetBtn').onclick=()=>{this.$('moreDialog').close();this.fullReset();};
  };

  app.init=async function(){
    const out=await originalInit();this.savedViews=loadCollection('views');this.watchAreas=loadCollection('areas');this.favorites=loadCollection('favorites');this.recentActivity=loadCollection('activity');
    this.installHistoryHooks();
    this.globe.addEventListener('select',e=>{const m=e.detail;if(m){this.recordActivity('contact',`Viewed ${m.name||m.type||'contact'}`,m);this.renderNearbyContext(m);}this.updateFavoriteButton();});
    this.registry.addEventListener('change',()=>{clearTimeout(this._timelineRefresh);this._timelineRefresh=setTimeout(()=>this.applyTimelineWindow(),180);});this.watchScanTimer=setInterval(()=>this.scanWatchAreas(),60000);this.scanWatchAreas();this.renderWatchCenter();this.applyTimelineWindow();return out;
  };

  app.renderScope=function(meta){const out=originalRenderScope(meta);if(meta)setTimeout(()=>this.renderNearbyContext(meta),0);return out;};
  if(originalPreset)app.applyPreset=async function(id){this.pushNavState('mode');const out=await originalPreset(id);this.recordActivity('mode',`Mode: ${id}`);return out;};
  if(originalWorldIntent)app.runWorldIntent=async function(raw){this.pushNavState('search');const ok=await originalWorldIntent(raw);if(ok)this.recordActivity('search',raw);return ok;};

  app.ensureWatchUi=function(){
    if(!document.querySelector('link[href="/src/ui/sblWatch.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/src/ui/sblWatch.css';document.head.appendChild(l);}
    const host=document.getElementById('app');
    if(!this.$('watchDialog'))host.insertAdjacentHTML('beforeend',`<dialog id='watchDialog' class='modal glass watch-dialog'><div class='modal-card watch-card'><div class='modal-head'><div><b>Watch Center</b><small>SAVED VIEWS · WATCH AREAS · FAVORITES · RECENT ACTIVITY</small></div><button id='watchCloseBtn' class='icon-btn' type='button'>✕</button></div><div class='watch-tabs'><button data-watch-tab='views' class='active'>VIEWS</button><button data-watch-tab='areas'>AREAS</button><button data-watch-tab='favorites'>FAVORITES</button><button data-watch-tab='activity'>ACTIVITY</button></div><section id='watchTabViews' class='watch-tab active'><div class='watch-create'><input id='saveViewName' placeholder='Name this view (optional)' maxlength='40'><button id='saveViewBtn' type='button'>SAVE CURRENT VIEW</button></div><div id='savedViewsList' class='watch-list'></div></section><section id='watchTabAreas' class='watch-tab'><div class='watch-create watch-area-create'><input id='watchAreaName' placeholder='Name this area (optional)' maxlength='40'><select id='watchRadius'><option value='16.0934'>10 mi radius</option><option value='40.2336'>25 mi radius</option><option value='80.4672' selected>50 mi radius</option><option value='160.934'>100 mi radius</option><option value='402.336'>250 mi radius</option></select><button id='addWatchBtn' type='button'>WATCH CURRENT AREA</button></div><div class='watch-note'>Watch Areas scan contacts/events already loaded in this open app. They are not background monitoring and do not run while ShadowNex is closed.</div><div id='watchAreasList' class='watch-list'></div></section><section id='watchTabFavorites' class='watch-tab'><button id='favoriteSelectedBtn' class='watch-primary' type='button'>☆ FAVORITE SELECTED SUBJECT</button><div id='favoritesList' class='watch-list'></div></section><section id='watchTabActivity' class='watch-tab'><div class='timeline-ribbon'><span>EVENT WINDOW</span><button data-window-hours='0.0833'>NOW</button><button data-window-hours='0.25'>15 MIN</button><button data-window-hours='1'>1 HR</button><button data-window-hours='6'>6 HR</button><button data-window-hours='24' class='active'>24 HR</button></div><button id='clearActivityBtn' class='ghost-btn' type='button'>CLEAR RECENT ACTIVITY</button><div id='activityList' class='watch-list'></div></section></div></dialog>`);
    const more=this.$('moreDialog')?.querySelector('.more-grid');
    if(more&&!this.$('moreLayersBtn'))more.insertAdjacentHTML('afterbegin',`<button id='moreLayersBtn' class='preset-card' type='button'><strong>Layers & Sources</strong><small>Open the full feed list.</small></button><button id='moreBackBtn' class='preset-card' type='button'><strong>Back / Undo View</strong><small>Return to the previous map state.</small></button><button id='moreResetBtn' class='preset-card' type='button'><strong>Full Reset</strong><small>Return ShadowNex to safe everyday defaults.</small></button>`);
  };

  app.openWatchCenter=function(tab='views'){this.renderWatchCenter();this.showWatchTab(tab);const d=this.$('watchDialog');if(!d.open)d.showModal();};
  app.showWatchTab=function(tab){for(const b of document.querySelectorAll('[data-watch-tab]'))b.classList.toggle('active',b.dataset.watchTab===tab);for(const el of document.querySelectorAll('.watch-tab'))el.classList.toggle('active',el.id===`watchTab${cap(tab)}`);};

  app.captureCurrentState=function(){const s=this.globe.state();return {camera:{lat:s.lat,lon:s.lon,alt:s.alt,heading:s.heading,pitch:s.pitch},layers:[...this.layers.values()].filter(l=>l.enabled).map(l=>l.id).concat(this.globe.trafficLayer?['traffic']:[]),lens:this.settings.lens||'normal',baseMap:this.globe.baseMapInfo().mode||'satellite',selected:compactMeta(this.globe.selected?.meta||{})};};
  app.saveCurrentView=function(){const name=this.$('saveViewName').value.trim()||`Saved view ${this.savedViews.length+1}`,view={id:makeId('view'),name,savedAt:Date.now(),...this.captureCurrentState()};this.savedViews=[view,...this.savedViews].slice(0,20);saveCollection('views',this.savedViews);this.$('saveViewName').value='';this.recordActivity('view',`Saved view: ${name}`);this.renderWatchCenter();this.toast(`Saved ${name}.`);};
  app.restoreSavedView=async function(id){const v=this.savedViews.find(x=>x.id===id);if(!v)return;this.pushNavState('saved view');await this.restoreState(v);this.recordActivity('view',`Opened saved view: ${v.name}`);this.$('watchDialog')?.close();};
  app.deleteSavedView=function(id){this.savedViews=this.savedViews.filter(x=>x.id!==id);saveCollection('views',this.savedViews);this.renderWatchCenter();};

  app.addCurrentWatchArea=function(){const p=this.globe.focusCoordinates(),radiusKm=Number(this.$('watchRadius').value)||80.4672,name=this.$('watchAreaName').value.trim()||`Watch area ${this.watchAreas.length+1}`,area={id:makeId('area'),name,lat:p.lat,lon:p.lon,radiusKm,createdAt:Date.now(),lastScan:null,hits:0,notable:0};this.watchAreas=[area,...this.watchAreas].slice(0,20);saveCollection('areas',this.watchAreas);this.$('watchAreaName').value='';this.recordActivity('watch',`Watching ${name} · ${fmtDistanceKm(radiusKm)} radius`);this.scanWatchAreas();this.renderWatchCenter();this.toast(`${name} added to Watch Areas.`);};
  app.deleteWatchArea=function(id){this.watchAreas=this.watchAreas.filter(x=>x.id!==id);saveCollection('areas',this.watchAreas);this.renderWatchCenter();};
  app.openWatchArea=function(id,brief=false){const a=this.watchAreas.find(x=>x.id===id);if(!a)return;this.pushNavState('watch area');this.globe.flyTo(a.lon,a.lat,Math.max(90000,a.radiusKm*2400));this.recordActivity('watch',`Opened watch area: ${a.name}`);this.$('watchDialog')?.close();if(brief)setTimeout(()=>this.openPrimeBrief?this.openPrimeBrief(a.name):this.openSituationBrief(),1000);};
  app.scanWatchAreas=function(){if(!this.watchAreas?.length)return;const items=[];for(const layer of this.layers.values())for(const e of layer.entities||[]){const m=this.contactMeta?.(e);if(m?.type==='CLUSTER')continue;const lat=Number(m?.latitude),lon=Number(m?.longitude);if(Number.isFinite(lat)&&Number.isFinite(lon))items.push(m);}for(const a of this.watchAreas){let hits=0,notable=0;for(const m of items){if(haversineKm({lat:a.lat,lon:a.lon},{lat:Number(m.latitude),lon:Number(m.longitude)})>a.radiusKm)continue;hits++;if(isNotable(m))notable++;}a.hits=hits;a.notable=notable;a.lastScan=Date.now();}saveCollection('areas',this.watchAreas);if(this.$?.('watchDialog')?.open)this.renderWatchCenter();};

  app.favoriteSelected=function(){const m=this.globe.selected?.meta;if(!m){this.toast('Select a subject first.');return;}const key=favKey(m),existing=this.favorites.find(x=>x.key===key);if(existing){this.favorites=this.favorites.filter(x=>x.key!==key);this.toast(`Removed ${m.name||m.type} from favorites.`);}else{this.favorites=[{id:makeId('fav'),key,addedAt:Date.now(),meta:compactMeta(m)},...this.favorites].slice(0,40);this.toast(`Favorited ${m.name||m.type}.`);this.recordActivity('favorite',`Favorited ${m.name||m.type||'subject'}`,m);}saveCollection('favorites',this.favorites);this.renderWatchCenter();this.updateFavoriteButton();};
  app.deleteFavorite=function(id){this.favorites=this.favorites.filter(x=>x.id!==id);saveCollection('favorites',this.favorites);this.renderWatchCenter();this.updateFavoriteButton();};
  app.openFavorite=function(id){const f=this.favorites.find(x=>x.id===id);if(!f)return;const hit=this.findFavoriteEntity(f);this.pushNavState('favorite');if(hit){this.globe.select(hit.meta,hit.entity);this.globe.smartFocus?.(hit.meta);this.toast(`Opened live ${hit.meta.name||hit.meta.type}.`);}else{const m=f.meta,lat=Number(m.latitude),lon=Number(m.longitude);if(Number.isFinite(lat)&&Number.isFinite(lon)){this.globe.flyTo(lon,lat,180000);this.toast(`${m.name||m.type}: showing last known position; subject is not currently loaded.`);}else this.toast('This favorite is not currently loaded.');}this.recordActivity('favorite',`Opened favorite: ${f.meta.name||f.meta.type}`);this.$('watchDialog')?.close();};
  app.findFavoriteEntity=function(f){for(const layer of this.layers.values())for(const e of layer.entities||[]){const m=this.contactMeta?.(e);if(m&&favKey(m)===f.key)return {meta:m,entity:e};}return null;};
  app.updateFavoriteButton=function(){const b=this.$?.('favoriteSelectedBtn'),m=this.globe.selected?.meta;if(!b)return;if(!m){b.textContent='☆ FAVORITE SELECTED SUBJECT';return;}b.textContent=this.favorites?.some(x=>x.key===favKey(m))?'★ REMOVE SELECTED FAVORITE':'☆ FAVORITE SELECTED SUBJECT';};

  app.recordActivity=function(kind,text,meta=null){if(!text)return;const row={id:makeId('act'),time:Date.now(),kind,text,meta:meta?compactMeta(meta):null};this.recentActivity=[row,...(this.recentActivity||[])].slice(0,40);saveCollection('activity',this.recentActivity);if(this.$?.('watchDialog')?.open)this.renderWatchCenter();};
  app.clearRecentActivity=function(){this.recentActivity=[];saveCollection('activity',[]);this.renderWatchCenter();};

  app.setActivityWindow=function(hours){this.activityWindowHours=hours;document.querySelectorAll('[data-window-hours]').forEach(b=>b.classList.toggle('active',Number(b.dataset.windowHours)===hours));this.applyTimelineWindow();this.recordActivity('timeline',`Event window: ${hours<1?'15 minutes':hours+' hours'}`);};
  app.applyTimelineWindow=function(){for(const id of ['earthquakes','fires']){const layer=this.layers.get(id);if(!layer)continue;for(const e of layer.entities||[]){const m=this.contactMeta?.(e);if(!m)continue;try{e.show=withinWindow(m,this.activityWindowHours);}catch{}}}this.globe.requestRender?.();};

  app.renderNearbyContext=function(meta){const box=this.$?.('scopeContent');if(!box||!meta)return;box.querySelector('.plain-context-card')?.remove();const hits=correlateContacts(meta,[...this.layers.values()],{radiusKm:160.934,limit:5});const card=document.createElement('section');card.className='plain-context-card';const counts={};for(const h of hits)counts[h.meta.type]=(counts[h.meta.type]||0)+1;const summary=Object.entries(counts).map(([k,v])=>`${v} ${humanType(k,v)}`).join(' · ');card.innerHTML=`<div class='context-head'><b>NEARBY CONTEXT</b><small>WITHIN 100 MILES · LOADED SOURCES</small></div>${hits.length?`<p>${escapeHtml(summary)}</p><div class='context-list'></div>`:`<p>No other loaded contacts are within 100 miles. This does not mean the area is empty; source coverage may be partial.</p>`}<div class='context-actions'><button type='button' class='context-fav'>☆ FAVORITE</button><button type='button' class='context-watch'>WATCH THIS AREA</button></div>`;const list=card.querySelector('.context-list');for(const h of hits){const b=document.createElement('button');b.type='button';b.innerHTML=`<span><strong>${escapeHtml(h.meta.name||h.meta.type||'Contact')}</strong><small>${escapeHtml(h.meta.type||'CONTACT')} · ${escapeHtml(h.relation||'nearby')}</small></span><em>${escapeHtml(fmtDistanceKm(h.distanceKm))}</em>`;b.onclick=()=>{this.globe.select(h.meta,h.entity);this.globe.smartFocus?.(h.meta);};list?.appendChild(b);}card.querySelector('.context-fav').onclick=()=>this.favoriteSelected();card.querySelector('.context-watch').onclick=()=>{const p=this.globe.selected?.meta;if(p&&Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude))){const a={id:makeId('area'),name:`${p.name||p.type} area`,lat:Number(p.latitude),lon:Number(p.longitude),radiusKm:80.4672,createdAt:Date.now(),lastScan:null,hits:0,notable:0};this.watchAreas=[a,...this.watchAreas].slice(0,20);saveCollection('areas',this.watchAreas);this.scanWatchAreas();this.toast(`Watching 50 miles around ${p.name||p.type}.`);this.recordActivity('watch',`Watching area around ${p.name||p.type}`,p);}};const tech=box.querySelector('.technical-data'),corr=box.querySelector('.correlation-box');if(tech)box.insertBefore(card,tech);else if(corr)box.insertBefore(card,corr);else box.appendChild(card);};

  app.installHistoryHooks=function(){if(this.globe.__sblHistory)return;const oldFly=this.globe.flyTo.bind(this.globe),oldHome=this.globe.home.bind(this.globe);this.globe.flyTo=(...args)=>{if(!this._restoringState)this.pushNavState('fly');return oldFly(...args);};this.globe.home=(...args)=>{if(!this._restoringState)this.pushNavState('home');return oldHome(...args);};this.globe.__sblHistory=true;};
  app.pushNavState=function(reason='view'){if(this._restoringState||!this.globe?.viewer)return;const state={reason,at:Date.now(),...this.captureCurrentState()},last=this.navHistory.at(-1);if(last&&nearState(last,state))return;this.navHistory.push(state);if(this.navHistory.length>12)this.navHistory.shift();};
  app.goBackState=async function(){const state=this.navHistory.pop();if(!state){this.toast('No previous ShadowNex view yet.');return;}await this.restoreState(state);this.toast('Returned to previous view.');};
  app.restoreState=async function(state){this._restoringState=true;try{const want=new Set(state.layers||[]);for(const l of this.layers.values())if(l.enabled&&!want.has(l.id))l.disable();if(this.globe.trafficLayer&&!want.has('traffic'))await this.setLayer('traffic',false);for(const id of want)await this.setLayer(id,true);if(state.baseMap)this.globe.setBaseMap(state.baseMap);if(state.lens)this.setLens(state.lens);this.renderLayers();const c=state.camera;if(c&&Number.isFinite(Number(c.lon))&&Number.isFinite(Number(c.lat)))this.globe.flyTo(Number(c.lon),Number(c.lat),Math.max(5000,Number(c.alt)||1200000));const sm=state.selected;if(sm&&Object.keys(sm).length){const f={key:favKey(sm),meta:sm},hit=this.findFavoriteEntity(f);if(hit)this.globe.select(hit.meta,hit.entity);else this.globe.clearSelection();}else this.globe.clearSelection();}finally{setTimeout(()=>{this._restoringState=false;},100);}};
  app.fullReset=async function(){this.pushNavState('reset');this._restoringState=true;try{for(const d of document.querySelectorAll('dialog[open]'))try{d.close()}catch{}this.globe.sceneDirector?.stop(false);this.globe.clearSelection();this.globe.cancelAnnotation?.();this.globe.clearAnnotations?.();for(const l of this.layers.values())if(l.enabled)l.disable();if(this.globe.trafficLayer)await this.setLayer('traffic',false);this.setLens('normal');this.globe.setBaseMap('satellite');this.activityWindowHours=24;await this.setLayer('earthquakes',true);await this.setLayer('aircraft',true);this.applyUiMode('simple');this.$('layerPanel')?.classList.remove('open');this.$('pulseTray')?.classList.add('collapsed');this.globe.home(true);this.applyTimelineWindow();this.recordActivity('reset','Full Reset');this.toast('ShadowNex reset to everyday defaults.');}finally{setTimeout(()=>{this._restoringState=false;},150);}};

  app.renderWatchCenter=function(){if(!this.$)return;this.renderSavedViews();this.renderWatchAreas();this.renderFavorites();this.renderActivity();this.updateFavoriteButton();};
  app.renderSavedViews=function(){const host=this.$('savedViewsList');if(!host)return;host.innerHTML=this.savedViews?.length?'':'<div class="watch-empty">No saved views yet.</div>';for(const v of this.savedViews||[]){const row=document.createElement('article');row.className='watch-item';row.innerHTML=`<div><strong>${escapeHtml(v.name)}</strong><small>${new Date(v.savedAt).toLocaleString('en-US')} · ${(v.layers||[]).length} layers</small></div><div class='watch-item-actions'><button data-open>OPEN</button><button data-delete>✕</button></div>`;row.querySelector('[data-open]').onclick=()=>this.restoreSavedView(v.id);row.querySelector('[data-delete]').onclick=()=>this.deleteSavedView(v.id);host.appendChild(row);}};
  app.renderWatchAreas=function(){const host=this.$('watchAreasList');if(!host)return;host.innerHTML=this.watchAreas?.length?'':'<div class="watch-empty">No Watch Areas yet.</div>';for(const a of this.watchAreas||[]){const row=document.createElement('article');row.className='watch-item';row.innerHTML=`<div><strong>${escapeHtml(a.name)}</strong><small>${escapeHtml(fmtDistanceKm(a.radiusKm))} radius · ${a.hits||0} loaded · ${a.notable||0} notable${a.lastScan?` · scanned ${age(a.lastScan)}`:''}</small></div><div class='watch-item-actions'><button data-brief>PRIME</button><button data-open>OPEN</button><button data-delete>✕</button></div>`;row.querySelector('[data-open]').onclick=()=>this.openWatchArea(a.id,false);row.querySelector('[data-brief]').onclick=()=>this.openWatchArea(a.id,true);row.querySelector('[data-delete]').onclick=()=>this.deleteWatchArea(a.id);host.appendChild(row);}};
  app.renderFavorites=function(){const host=this.$('favoritesList');if(!host)return;host.innerHTML=this.favorites?.length?'':'<div class="watch-empty">No favorite subjects yet.</div>';for(const f of this.favorites||[]){const m=f.meta||{},row=document.createElement('article');row.className='watch-item';row.innerHTML=`<div><strong>${escapeHtml(m.name||m.type||'Favorite')}</strong><small>${escapeHtml(m.type||'CONTACT')} · ${escapeHtml(m.source||'public source')}</small></div><div class='watch-item-actions'><button data-open>OPEN</button><button data-delete>✕</button></div>`;row.querySelector('[data-open]').onclick=()=>this.openFavorite(f.id);row.querySelector('[data-delete]').onclick=()=>this.deleteFavorite(f.id);host.appendChild(row);}};
  app.renderActivity=function(){const host=this.$('activityList');if(!host)return;host.innerHTML=this.recentActivity?.length?'':'<div class="watch-empty">Recent ShadowNex actions will appear here.</div>';for(const a of this.recentActivity||[]){const row=document.createElement('article');row.className='activity-item';row.innerHTML=`<span>${escapeHtml(iconFor(a.kind))}</span><div><strong>${escapeHtml(a.text)}</strong><small>${new Date(a.time).toLocaleString('en-US')}</small></div>`;host.appendChild(row);}};
}

function favKey(m={}){return `${String(m.type||'CONTACT').toUpperCase()}:${String(m.id||m.name||'').toUpperCase()}`;}
function cap(s=''){return s.charAt(0).toUpperCase()+s.slice(1);}
function humanType(type,count){const m={AIRCRAFT:'aircraft',VESSEL:count===1?'vessel':'vessels',SATELLITE:count===1?'satellite':'satellites',CCTV:count===1?'camera':'cameras',EARTHQUAKE:count===1?'earthquake':'earthquakes',FIRE:count===1?'fire event':'fire events',LAUNCH:count===1?'launch':'launches'};return m[type]||String(type||'item').toLowerCase();}
function isNotable(m={}){return (m.type==='EARTHQUAKE'&&Number(m.magnitude)>=4)||(m.type==='FIRE')||(m.type==='AIRCRAFT'&&m.militaryLikely)||(m.type==='LAUNCH');}
function age(ts){const min=Math.max(0,Math.round((Date.now()-ts)/60000));return min<1?'just now':min<60?`${min}m ago`:`${Math.round(min/60)}h ago`;}
function iconFor(k){return ({contact:'◎',search:'⌕',view:'▣',watch:'◉',favorite:'★',mode:'◇',timeline:'↔',reset:'↺'})[k]||'•';}
function nearState(a,b){const ac=a.camera||{},bc=b.camera||{};return Math.abs(Number(ac.lat||0)-Number(bc.lat||0))<.01&&Math.abs(Number(ac.lon||0)-Number(bc.lon||0))<.01&&Math.abs(Number(ac.alt||0)-Number(bc.alt||0))<5000&&(a.layers||[]).join('|')===(b.layers||[]).join('|');}