import { escapeHtml } from '../core/geo.js';
import { buildSituation, inViewport, situationSummary } from '../core/situation.js';

export function installSituationEnhancements(app){
  app.locationStartKey='shadownex.prime.locationStart.v1';
  const originalInit=app.init.bind(app),originalBind=app.bindUi.bind(app),originalShowWelcome=app.showWelcome.bind(app);

  app.showWelcome=function(force=false){if(force)return originalShowWelcome(true);try{if(localStorage.getItem(this.locationStartKey)==='done')return;}catch{}this.showLocationStart();};
  app.init=async function(){const result=await originalInit();this.situationTimer=setInterval(()=>this.refreshSituationAwareness(),20000);this.globe.viewer.camera.moveEnd.addEventListener(()=>{clearTimeout(this._situationMove);this._situationMove=setTimeout(()=>this.refreshSituationAwareness(),250);});this.refreshSituationAwareness();return result;};
  app.bindUi=function(){originalBind();this.ensureSituationUi();this.$('situationBtn').onclick=()=>this.openSituationBrief();this.$('locationNearBtn').onclick=()=>this.startNearMe();this.$('locationSearchBtn').onclick=()=>{this.finishLocationStart();this.openSearch();};this.$('locationExploreBtn').onclick=()=>{this.finishLocationStart();this.resetView();};this.$('locationStartClose').onclick=()=>this.finishLocationStart();this.$('situationCloseBtn').onclick=()=>this.$('situationDialog').close();};

  app.ensureSituationUi=function(){
    if(!document.querySelector('link[href="/src/ui/situation.css"]')){const link=document.createElement('link');link.rel='stylesheet';link.href='/src/ui/situation.css';document.head.appendChild(link);}
    const host=document.getElementById('app');
    if(!this.$('situationBtn'))host.insertAdjacentHTML('beforeend','<button id="situationBtn" class="situation-fab" type="button"><span>WHAT’S HAPPENING HERE?</span><b id="situationAlertCount" class="hidden">0</b></button>');
    if(!this.$('locationStartDialog'))host.insertAdjacentHTML('beforeend',`<dialog id="locationStartDialog" class="modal glass location-start"><div class="modal-card"><div class="modal-head"><div><b>Where do you want to start?</b><small>CHOOSE A STARTING POINT — LOCATION IS OPTIONAL</small></div><button id="locationStartClose" class="icon-btn" type="button">✕</button></div><p class="location-intro">ShadowNex works without your location. Choose one simple way to enter the live map.</p><div class="location-choices"><button id="locationNearBtn" class="start-card" type="button"><strong>Near Me</strong><small>Ask for device location only after you tap this button.</small></button><button id="locationSearchBtn" class="start-card" type="button"><strong>Search a Place</strong><small>City, country, landmark, coordinates, or an active contact.</small></button><button id="locationExploreBtn" class="start-card" type="button"><strong>Explore the World</strong><small>Start with the full Earth and browse live public data.</small></button></div><div id="locationStartStatus" class="location-status">You can change this anytime with Search, Home, or the globe.</div></div></dialog>`);
    if(!this.$('situationDialog'))host.insertAdjacentHTML('beforeend',`<dialog id="situationDialog" class="modal glass situation-dialog"><div class="modal-card command-card"><div class="modal-head"><div><b>Regional / Daily Brief</b><small>WHAT MATTERS IN THE CURRENT VIEW · LIVE + RECENT PUBLIC FEEDS</small></div><button id="situationCloseBtn" class="icon-btn" type="button">✕</button></div><div id="situationOverview" class="situation-overview"></div><div id="situationCards" class="situation-cards"></div><div class="situation-footnote">Based only on currently loaded public/open-source feeds. Missing, delayed, or unavailable sources are not treated as “no activity.”</div></div></dialog>`);
  };

  app.showLocationStart=function(){const d=this.$?.('locationStartDialog');if(d&&!d.open)d.showModal();};
  app.finishLocationStart=function(){try{localStorage.setItem(this.locationStartKey,'done')}catch{}const d=this.$('locationStartDialog');if(d?.open)d.close();};
  app.startNearMe=function(){const status=this.$('locationStartStatus');if(!navigator.geolocation){status.textContent='Device location is not available here. Use Search a Place instead.';return;}status.textContent='Requesting your device location…';navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude,lon=pos.coords.longitude;this.finishLocationStart();this.globe.flyTo(lon,lat,420000);this.toast('Centered near your device location.');setTimeout(()=>this.openSituationBrief(),1100);},err=>{status.textContent=err.code===1?'Location permission was not granted. Search and Explore still work normally.':'Could not get device location. Search and Explore still work normally.';},{enableHighAccuracy:false,timeout:10000,maximumAge:300000});};

  app.collectSituationItems=function(){const bounds=this.globe.rectangle(),center=this.globe.focusCoordinates(),items=[],seen=new Set();for(const layer of this.layers.values()){const state=this.registry.get(layer.id);for(const entity of layer.entities||[]){const meta=this.contactMeta?.(entity);if(!meta||meta.type==='CLUSTER'||!inViewport(meta,bounds))continue;const key=`${meta.type}:${meta.id||meta.name||meta.latitude+','+meta.longitude}`;if(seen.has(key))continue;seen.add(key);items.push({meta,entity,layerId:layer.id,sourceUpdatedAt:state?.updatedAt,sourceStatus:state?.status});}}return {items,bounds,center};};
  app.currentSituation=function(){const {items,bounds,center}=this.collectSituationItems();return buildSituation(items,{center,bounds,limit:5});};
  app.ageLabel=function(ts){if(!ts)return 'time unavailable';const s=Math.max(0,Math.round((Date.now()-ts)/1000));if(s<60)return `${s}s ago`;const m=Math.round(s/60);if(m<60)return `${m}m ago`;const h=Math.round(m/60);return h<48?`${h}h ago`:`${Math.round(h/24)}d ago`;};
  app.reasonText=function(rank){return rank.reasons.length?rank.reasons.join(' · '):'surfaced from current public-source activity';};
  app.openSituationBrief=function(){const snap=this.currentSituation(),overview=this.$('situationOverview'),cards=this.$('situationCards');const countParts=Object.entries(snap.counts).sort((a,b)=>b[1]-a[1]).slice(0,4).map(([k,v])=>`${v} ${k.toLowerCase().replace('_',' ')}`);overview.innerHTML=`<strong>${snap.total?`${snap.total} loaded contacts/events in this view`:'No loaded contacts/events in this view'}</strong><small>${escapeHtml(countParts.join(' · ')||'Turn on a guided mode or zoom to another area.')}</small>${snap.alerts.length?`<em>${snap.alerts.length} notable item${snap.alerts.length===1?'':'s'} surfaced</em>`:''}`;cards.innerHTML='';if(!snap.top.length){cards.innerHTML='<div class="situation-empty">No active loaded feed has an item in this view yet. This does not mean nothing is happening — a source may be off, loading, unavailable, or outside its coverage.</div>';}for(const item of snap.top)this.renderSituationCard(item,cards);const d=this.$('situationDialog');if(!d.open)d.showModal();};
  app.renderSituationCard=function(item,host){const {meta,rank}=item,card=document.createElement('article');card.className=`situation-card ${rank.level.toLowerCase()}`;const label=rank.score>=82?'HIGH PRIORITY':rank.score>=68?'NOTABLE':rank.level;card.innerHTML=`<div class="situation-card-head"><span>${escapeHtml(label)}</span><b>${rank.score}</b></div><strong>${escapeHtml(meta.name||meta.type||'Contact')}</strong><p>${escapeHtml(situationSummary(meta,rank))}</p><small><b>WHY SHOWN:</b> ${escapeHtml(this.reasonText(rank))}</small><div class="situation-source">${escapeHtml(meta.source||'Public source')}${rank.timestamp?` · ${escapeHtml(this.ageLabel(rank.timestamp))}`:''}</div><div class="situation-actions"><button type="button" class="ghost-btn view-contact">VIEW ON GLOBE</button>${meta.url?'<button type="button" class="ghost-btn open-source">SOURCE</button>':''}</div>`;card.querySelector('.view-contact').onclick=()=>{this.globe.select(meta,item.entity);const lon=Number(meta.longitude),lat=Number(meta.latitude);if(Number.isFinite(lon)&&Number.isFinite(lat))this.globe.flyTo(lon,lat,Math.max(160000,Number(meta.altitude)||350000));this.$('situationDialog').close();};const source=card.querySelector('.open-source');if(source)source.onclick=()=>window.open(meta.url,'_blank','noopener');host.appendChild(card);};

  app.refreshSituationAwareness=function(){if(!this.globe?.viewer)return;const snap=this.currentSituation(),badge=this.$?.('situationAlertCount');if(badge){badge.textContent=String(snap.alerts.length);badge.classList.toggle('hidden',!snap.alerts.length);}this.applyImportanceVisuals(snap.ranked);};
  app.applyImportanceVisuals=function(ranked=[]){const C=window.Cesium;if(!C)return;for(const item of ranked){const point=item.entity?.point;if(!point)continue;let base=item.entity.__snxBasePixelSize;if(!Number.isFinite(base)){try{base=Number(point.pixelSize?.getValue?.(this.globe.viewer.clock.currentTime)??point.pixelSize)||6;}catch{base=6}item.entity.__snxBasePixelSize=base;}const factor=item.rank.score>=82?1.45:item.rank.score>=68?1.24:1;let baseOutline=item.entity.__snxBaseOutlineWidth;if(!Number.isFinite(baseOutline)){try{baseOutline=Number(point.outlineWidth?.getValue?.(this.globe.viewer.clock.currentTime)??point.outlineWidth)||1;}catch{baseOutline=1}item.entity.__snxBaseOutlineWidth=baseOutline;}try{point.pixelSize=new C.ConstantProperty(Math.max(4,base*factor));point.outlineWidth=new C.ConstantProperty(item.rank.score>=82?Math.max(2,baseOutline):baseOutline);}catch{}}this.globe.requestRender?.();};
}
