const KM_TO_MI=.6213711922,M_TO_FT=3.280839895;
const mi=km=>km*KM_TO_MI,feet=m=>m*M_TO_FT,fmtMi=km=>{const v=mi(Number(km));return Number.isFinite(v)?(v<10?v.toFixed(1):Math.round(v).toLocaleString('en-US'))+' mi':'—'},fmtFt=m=>Number.isFinite(Number(m))?Math.round(feet(Number(m))).toLocaleString('en-US')+' ft':'—',fmtSpace=m=>Number.isFinite(Number(m))?((Number(m)/1609.344)>=100?Math.round(Number(m)/1609.344).toLocaleString('en-US'):(Number(m)/1609.344).toFixed(1))+' mi':'—';
export function installUnitEnhancements(app){
  const oldPrimary=app.primaryContactRows?.bind(app),oldValue=app.contactValue?.bind(app),oldSummary=app.humanSummary?.bind(app),oldRender=app.renderScope.bind(app),oldReason=app.reasonText?.bind(app),oldInit=app.init.bind(app),oldRun=app.command.run.bind(app.command);
  app.primaryContactRows=function(m){if(m.type==='AIRCRAFT'){return [['Altitude',fmtFt(m.altitude)],['Speed',Number.isFinite(Number(m.velocity))?`${Math.round(Number(m.velocity)*1.94384)} kt`:null],['Source',m.source]].filter(x=>x[1]);}if(m.type==='SATELLITE'){return [['Altitude',fmtSpace(m.altitude)],['Position','ESTIMATED'],['Source',m.source]].filter(x=>x[1]);}if(m.type==='EARTHQUAKE'){return [['Magnitude',Number.isFinite(Number(m.magnitude))?`M${Number(m.magnitude).toFixed(1)}`:null],['Depth',Number.isFinite(Number(m.depthKm))?fmtMi(Number(m.depthKm)):null],['Source',m.source]].filter(x=>x[1]);}return oldPrimary?oldPrimary(m):[];};
  app.contactValue=function(k,v){if(k==='altitude')return this._unitMeta?.type==='SATELLITE'?fmtSpace(v):fmtFt(v);if(k==='depthKm')return fmtMi(v);if(k==='verticalRate'&&Number.isFinite(Number(v)))return `${Math.round(feet(Number(v))*60).toLocaleString('en-US')} ft/min`;return oldValue?oldValue(k,v):String(v);};
  app.humanSummary=function(m){if(m.type==='AIRCRAFT'){const name=String(m.name||'Aircraft'),alt=Number(m.altitude),spd=Number(m.velocity),hdg=Number(m.heading);if(m.onGround)return `${name} is reported on the ground by ${m.source||'the public source'}.`;let s=`${name} is airborne`;if(Number.isFinite(alt))s+=` at ${fmtFt(alt)}`;if(Number.isFinite(spd))s+=`, moving at about ${Math.round(spd*1.94384)} kt`;if(Number.isFinite(hdg))s+=` on heading ${Math.round((hdg%360+360)%360)}°`;return s+'.';}if(m.type==='EARTHQUAKE'){const mag=Number(m.magnitude),depth=Number(m.depthKm);return `${Number.isFinite(mag)?`Magnitude ${mag.toFixed(1)} earthquake`:'Earthquake'} near ${m.name||'this area'}${Number.isFinite(depth)?` at ${fmtMi(depth)} depth`:''}.`;}return oldSummary?oldSummary(m):String(m.name||m.type||'Contact');};
  app.renderScope=function(meta){this._unitMeta=meta;oldRender(meta);this._unitMeta=null;setTimeout(()=>{this.$?.('scopeContent')?.querySelectorAll('.correlation-row>span').forEach(s=>{const m=s.textContent.match(/^([0-9.]+)\s*KM$/i);if(m)s.textContent=fmtMi(Number(m[1]));});},0);};
  if(oldReason)app.reasonText=function(rank){return String(oldReason(rank)).replace(/([0-9.]+)\s*km\b/gi,(_,n)=>fmtMi(Number(n)));};
  app.command.run=async raw=>String(await oldRun(raw)).replace(/([0-9.]+)\s*km\b/gi,(_,n)=>fmtMi(Number(n)));
  app.updateCockpitHud=function(){if(!this.globe?.cockpit||!this.globe.selected?.meta||!this.$)return;const m=this.globe.selected.meta,heading=Number(m.heading),speed=Number(m.velocity??m.speed),alt=Number(m.altitude);this.$('cockpitTarget').textContent=String(m.name||m.type||'CONTACT').slice(0,24);this.$('cockpitCohort').textContent=String(m.cohort||m.type||'CONTACT').slice(0,32);this.$('cockpitHeading').textContent=Number.isFinite(heading)?`${String(Math.round((heading%360+360)%360)).padStart(3,'0')}°`:'---°';this.$('cockpitSpeed').textContent=`SPD ${Number.isFinite(speed)?(m.type==='AIRCRAFT'?`${Math.round(speed*1.94384)} KT`:`${speed.toFixed(1)} KT`):'—'}`;this.$('cockpitAltitude').textContent=m.type==='SATELLITE'?fmtSpace(alt):fmtFt(alt);this.$('cockpitSource').textContent=String(m.source||'PUBLIC SOURCE').toUpperCase().slice(0,28);};
  app.init=async function(){const out=await oldInit();const originalFinish=this.globe.finishAnnotation.bind(this.globe);this.globe.finishAnnotation=()=>{const result=originalFinish();setTimeout(()=>{for(const e of this.globe.annotation?.entities||[]){let txt;try{txt=e.label?.text?.getValue?.(this.globe.viewer.clock.currentTime)??e.label?.text}catch{}if(typeof txt!=='string')continue;let m=txt.match(/^([0-9.]+) km²$/);if(m)e.label.text=`${(Number(m[1])*.3861021585).toFixed(1)} sq mi`;m=txt.match(/^([0-9.]+) km$/);if(m)e.label.text=fmtMi(Number(m[1]));}},0);return result;};return out;};
}
