import { BaseLayer } from './BaseLayer.js';
import { TrailStore } from '../core/trails.js';
export class AircraftLayer extends BaseLayer{
  constructor(app){super(app,{id:'aircraft',label:'Aircraft',source:'ADSB.lol / optional OpenSky',description:'Public ADS-B/MLAT aircraft around the current globe view',interval:18000});this.byId=new Map();this.trails=new TrailStore({maxPoints:26,maxAgeMs:16*60*1000,minMoveKm:.35});this.cameraRefresh=null;app.globe.addEventListener('camera',()=>{if(!this.enabled)return;clearTimeout(this.cameraRefresh);this.cameraRefresh=setTimeout(()=>this.refresh().catch(e=>this.fail(e)),900);});}
  async refresh(){const focus=this.app.globe.focusCoordinates(),camera=this.app.globe.state(),radius=Math.max(75,Math.min(250,Math.round((Number(camera.alt)||1000000)/5000)));const q=new URLSearchParams({lat:focus.lat.toFixed(4),lon:focus.lon.toFixed(4),radius:String(radius)});const r=await fetch(`/api/aircraft?${q}`,{signal:AbortSignal.timeout(13000)});if(!r.ok){let detail='';try{const e=await r.json();detail=e?.message||e?.error||'';}catch{}throw new Error(detail||`Aircraft HTTP ${r.status}`);}const data=await r.json();const rows=data.states||[],C=window.Cesium,limit=this.app.densityLimit(350,700,1200),seen=new Set(),source=String(data._source||'Public ADS-B');let n=0;
    for(const s of rows){if(n>=limit)break;const lon=s[5],lat=s[6],alt=s[7]??s[13];if(!Number.isFinite(lon)||!Number.isFinite(lat))continue;const id=String(s[0]||'');if(!id)continue;seen.add(id);const callsign=(s[1]||id||'UNKNOWN').trim();const heading=Number(s[10])||0,velocity=Number(s[9])||0;const militaryLikely=/^(RCH|CNV|EVAC|REACH|NATO|FORTE|DUKE|VIPER|HOSS|PAT|NAVY|ARMY)/i.test(callsign);const meta={type:'AIRCRAFT',id,name:callsign,country:s[2],longitude:lon,latitude:lat,altitude:alt,velocity,heading,verticalRate:s[11],onGround:!!s[8],source,militaryLikely,cohort:militaryLikely?'MILITARY-LIKELY HEURISTIC':s[8]?'GROUND':'AIRBORNE CIVIL',accuracy:`PUBLIC ADS-B / MLAT · ${source}`};const cart=C.Cartesian3.fromDegrees(lon,lat,Math.max(alt||0,50));let rec=this.byId.get(id);
      if(!rec){const entity=this.add({position:cart,point:{pixelSize:militaryLikely?8:6,color:militaryLikely?C.Color.ORANGE:C.Color.CYAN,outlineColor:C.Color.BLACK,outlineWidth:1,distanceDisplayCondition:new C.DistanceDisplayCondition(0,8500000)},label:{text:callsign,font:'9px monospace',fillColor:C.Color.WHITE,showBackground:true,backgroundColor:new C.Color(0,0,0,.55),pixelOffset:new C.Cartesian2(0,-13),distanceDisplayCondition:new C.DistanceDisplayCondition(0,1500000)},properties:{snxMeta:meta}});const trailEntity=this.add({polyline:{positions:[],width:1.5,material:(militaryLikely?C.Color.ORANGE:C.Color.CYAN).withAlpha(.42),distanceDisplayCondition:new C.DistanceDisplayCondition(0,3200000)}});rec={entity,trailEntity,lastSeen:Date.now()};this.byId.set(id,rec);}else{rec.entity.position=cart;rec.entity.properties.snxMeta=meta;if(this.app.globe.selected?.entity===rec.entity)this.app.globe.selected.meta=meta;rec.entity.label.text=callsign;rec.lastSeen=Date.now();}
      const trail=this.trails.push(id,{lat,lon,alt});rec.trailEntity.polyline.positions=trail.map(p=>C.Cartesian3.fromDegrees(p.lon,p.lat,Math.max(p.alt||0,60)));n++;}
    const now=Date.now();for(const [id,rec] of this.byId){if(seen.has(id)||now-rec.lastSeen<90000)continue;this.app.globe.viewer.entities.remove(rec.entity);this.app.globe.viewer.entities.remove(rec.trailEntity);this.entities=this.entities.filter(e=>e!==rec.entity&&e!==rec.trailEntity);this.byId.delete(id);this.trails.remove(id);}this.trails.prune(this.byId.keys(),now);const radiusNote=data._reducedRadius?' · 120 NM retry':'';this.setHealthy(n,`${source} · ${rows.length} states · ${radius} NM view${radiusNote} · ${this.byId.size} tracked`);}
  clear(){super.clear();this.byId.clear();this.trails.clear();clearTimeout(this.cameraRefresh);}
}
