import { BaseLayer } from './BaseLayer.js';
export class ContextLayer extends BaseLayer{
 constructor(app){super(app,{id:'context',label:'Military + Infrastructure',source:'OpenStreetMap / Overpass',description:'Visible-area contextual sites',interval:180000});this.moveTimer=null;}
 async enable(){await super.enable();this.moveTimer=()=>{clearTimeout(this._delay);this._delay=setTimeout(()=>this.refresh().catch(e=>this.fail(e)),1000)};this.app.globe.viewer.camera.moveEnd.addEventListener(this.moveTimer);}
 disable(){if(this.moveTimer)this.app.globe.viewer.camera.moveEnd.removeEventListener(this.moveTimer);this.moveTimer=null;super.disable();}
 async refresh(){const b=this.app.globe.rectangle();if(!b)throw new Error('No visible globe rectangle');const span=Math.abs(b.east-b.west)*Math.abs(b.north-b.south);if(span>1200){this.clear();this.app.registry.set(this.id,{status:'STANDBY',count:0,note:'Zoom in to map contextual sites'});return;}
   const box=`${b.south.toFixed(4)},${b.west.toFixed(4)},${b.north.toFixed(4)},${b.east.toFixed(4)}`;const q=`[out:json][timeout:20];(nwr[landuse=military](${box});nwr[military](${box});nwr[man_made="data_centre"](${box});nwr[waterway=dam](${box}););out center tags 150;`;
   const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'data='+encodeURIComponent(q)});if(!r.ok)throw new Error(`Overpass HTTP ${r.status}`);const d=await r.json();this.clear();const C=window.Cesium;let n=0;for(const el of d.elements||[]){const lat=el.lat??el.center?.lat,lon=el.lon??el.center?.lon;if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const t=el.tags||{};const military=t.military||t.landuse==='military';const kind=military?(t.military||'military'):(t.man_made==='data_centre'?'data center':t.waterway||'infrastructure');const meta={type:military?'MILITARY_SITE':'INFRASTRUCTURE',name:t.name||kind.toUpperCase(),kind,operator:t.operator,latitude:lat,longitude:lon,source:'OpenStreetMap / Overpass'};this.add({position:C.Cartesian3.fromDegrees(lon,lat,40),point:{pixelSize:7,color:military?C.Color.RED:C.Color.YELLOW,outlineColor:C.Color.BLACK,outlineWidth:1},properties:{snxMeta:meta}});n++;}this.setHealthy(n,'Visible-area query');}
}
