import { BaseLayer } from './BaseLayer.js';
import { TrailStore } from '../core/trails.js';
export class VesselLayer extends BaseLayer{
 constructor(app){super(app,{id:'vessels',label:'Live Vessels',source:'AISStream',description:'Optional live AIS positions + trails',interval:60000});this.ws=null;this.byMmsi=new Map();this.trails=new TrailStore({maxPoints:36,maxAgeMs:45*60*1000,minMoveKm:.08});}
 async enable(){if(this.enabled)return;const key=this.app.settings.aisKey;if(!key){this.enabled=false;this.app.registry.set(this.id,{status:'STANDBY',note:'AISStream key required'});return;}this.enabled=true;this.connect(key);}
 connect(key){try{this.app.registry.set(this.id,{status:'SYNC',note:'Opening AIS stream'});this.ws=new WebSocket('wss://stream.aisstream.io/v0/stream');this.ws.onopen=()=>{const b=this.app.globe.rectangle();const boxes=b?[[[b.south,b.west],[b.north,b.east]]]:[[[-90,-180],[90,180]]];this.ws.send(JSON.stringify({APIKey:key,BoundingBoxes:boxes,FilterMessageTypes:['PositionReport']}));this.app.registry.set(this.id,{status:'LIVE',note:'AIS stream connected',updatedAt:Date.now()});};this.ws.onmessage=e=>this.onMessage(e.data);this.ws.onerror=()=>this.app.registry.set(this.id,{status:'DEGRADED',note:'AIS stream error'});this.ws.onclose=()=>{if(this.enabled)this.app.registry.set(this.id,{status:'STALE',note:'AIS stream closed'});};}catch(e){this.fail(e);}}
 onMessage(raw){let d;try{d=JSON.parse(raw)}catch{return}const p=d.Message?.PositionReport;if(!p)return;const meta0=d.MetaData||{},lat=Number(p.Latitude??meta0.latitude),lon=Number(p.Longitude??meta0.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const mmsi=String(p.UserID||meta0.MMSI||'');if(!mmsi)return;const meta={type:'VESSEL',id:mmsi,name:meta0.ShipName||`MMSI ${mmsi}`,latitude:lat,longitude:lon,speed:p.Sog,heading:p.TrueHeading||p.Cog,source:'AISStream',cohort:Number(p.Sog)>15?'HIGH-SPEED VESSEL':'MARITIME CONTACT'};const C=window.Cesium;let rec=this.byMmsi.get(mmsi);if(!rec){const entity=this.add({position:C.Cartesian3.fromDegrees(lon,lat,10),point:{pixelSize:7,color:C.Color.DODGERBLUE,outlineColor:C.Color.WHITE,outlineWidth:1},properties:{snxMeta:meta}});const trailEntity=this.add({polyline:{positions:[],width:1.5,material:C.Color.DODGERBLUE.withAlpha(.45)}});rec={entity,trailEntity};this.byMmsi.set(mmsi,rec);}else{rec.entity.position=C.Cartesian3.fromDegrees(lon,lat,10);rec.entity.properties.snxMeta=meta;if(this.app.globe.selected?.entity===rec.entity)this.app.globe.selected.meta=meta;}const trail=this.trails.push(mmsi,{lat,lon,alt:10});rec.trailEntity.polyline.positions=trail.map(x=>C.Cartesian3.fromDegrees(x.lon,x.lat,12));this.app.registry.set(this.id,{status:'LIVE',count:this.byMmsi.size,updatedAt:Date.now(),note:'AIS stream connected'});}
 disable(){this.enabled=false;try{this.ws?.close()}catch{}this.ws=null;this.byMmsi.clear();this.trails.clear();super.disable();}
 async refresh(){}
}
