import {readFile} from 'node:fs/promises';
import {parseWorldIntent,overallConnection,imageryZoom,ageAlpha} from '../src/core/worldQuery.js';
let pass=0,fail=0;const check=(ok,msg)=>{if(ok){console.log('✓',msg);pass++;}else{console.error('✗',msg);fail++;}};const read=p=>readFile(new URL(`../${p}`,import.meta.url),'utf8');
const [ui,decor,api,main,profile,launch,quake,fire,css]=await Promise.all(['src/ui/sblUi.js','src/ui/mapDecor.js','api/imagery.js','src/main.js','src/ui/profileEnhancements.js','src/layers/LaunchLayer.js','src/layers/EarthquakeLayer.js','src/layers/FireLayer.js','src/ui/sbl.css'].map(read));
const cam=parseWorldIntent('show cameras in Oklahoma City'),air=parseWorldIntent('aircraft near Dallas'),iss=parseWorldIntent('find the ISS'),big=parseWorldIntent('biggest earthquake today');
check(cam?.layer==='cctv'&&/Oklahoma City/i.test(cam.place),'intent parser understands cameras in Oklahoma City');
check(air?.layer==='aircraft'&&/Dallas/i.test(air.place),'intent parser understands aircraft near Dallas');
check(iss?.kind==='contact'&&iss.layer==='satellites'&&big?.kind==='biggest','intent parser understands ISS and strongest-earthquake requests');
check(overallConnection([{enabled:true,status:'LIVE'},{enabled:true,status:'DEGRADED'}],true)==='PARTIAL'&&overallConnection([{enabled:true,status:'DEGRADED'}],true)==='OFFLINE','coverage state reduces feeds to LIVE/PARTIAL/OFFLINE');
check(imageryZoom(100)>imageryZoom(100000),'imagery metadata zoom increases as camera gets closer');
check(ageAlpha({type:'AIRCRAFT',updatedAt:Date.now()-400000},{status:'LIVE'})<1,'aging aircraft receives stale visual fade');
check(ui.includes('simpleHub')&&ui.includes('runWorldIntent')&&css.includes('.sbl-simple .simple-hub'),'Simple Mode world-query hub is installed');
check(ui.includes('openSituationBriefV2')&&ui.includes('brief-source-grid'),'What’s Here v2 coverage summary is installed');
check(api.includes('World_Imagery/MapServer/0/query')&&api.includes('SRC_RES')&&api.includes('SRC_DATE2'),'imagery inspector queries source/date/resolution metadata');
check(decor.includes('SPECS')&&decor.includes('smartFocus')&&decor.includes('ageAlpha'),'distinct map symbols, smart selection camera, and fading are installed');
check(profile.includes('AIRCRAFT PROFILE')&&profile.includes('SATELLITE PROFILE')&&profile.includes('LAUNCH PROFILE')&&profile.includes('EARTHQUAKE PROFILE')&&profile.includes('FIRE PROFILE')&&profile.includes('VESSEL PROFILE'),'rich profile coverage spans major selectable subjects');
check(profile.includes('Specific mission/purpose is not publicly identified')||profile.includes('Specific mission'),'aircraft card preserves no-invented-mission wording');
check(launch.includes('missionDescription')&&launch.includes('rocket:')&&quake.includes('significance')&&fire.includes('updatedAt'),'richer launch/quake/fire source metadata is captured');
check(main.includes('installSblUi(app)')&&main.includes('installMapDecor(app)'),'SBL modules are wired into app boot');
console.log(`\nSBL QA: ${pass} passed, ${fail} failed`);process.exitCode=fail?1:0;