import { polygonAreaKm2, polylineKm } from '../core/geo.js';
export class AnnotationController extends EventTarget{
  constructor(globe){super();this.globe=globe;this.viewer=globe.viewer;this.mode=null;this.points=[];this.entities=[];this.preview=[];this.draftVertices=[];this.lastRoute=[];}
  arm(mode){if(!['mark','route','area','measure'].includes(mode))return;this.cancel(false);this.mode=mode;this.points=[];document.body.classList.add('mark-cursor');this.emit(`${mode.toUpperCase()} armed`);}
  isArmed(){return !!this.mode}
  handleClick(screenPosition){if(!this.mode)return false;const geo=this.pick(screenPosition);if(!geo)return true;this.points.push(geo);if(this.mode==='mark'){this.drawMark(geo);this.finish();}else{this.drawVertex(geo);this.updatePreview();this.emit(`${this.mode.toUpperCase()} point added`);}return true;}
  finish(){if(!this.mode)return null;const mode=this.mode,pts=[...this.points];if(mode==='route'&&pts.length>=2){this.drawPolyline(pts,'route');this.lastRoute=pts;}else if(mode==='measure'&&pts.length>=2){this.drawPolyline(pts,'measure');this.drawSummaryLabel(pts.at(-1),`${polylineKm(pts).toFixed(1)} km`);}else if(mode==='area'&&pts.length>=3){this.drawPolygon(pts);this.drawSummaryLabel(centroid(pts),`${polygonAreaKm2(pts).toFixed(1)} km²`);}else if(mode!=='mark'){this.cancel(false);this.emit('Not enough points');return null;}
    this.clearPreview();this.entities.push(...this.draftVertices);this.draftVertices=[];this.mode=null;this.points=[];document.body.classList.remove('mark-cursor');this.emit(`${mode.toUpperCase()} saved`);return {mode,points:pts};
  }
  cancel(emit=true){this.clearPreview();for(const e of this.draftVertices)this.viewer.entities.remove(e);this.draftVertices=[];this.mode=null;this.points=[];document.body.classList.remove('mark-cursor');if(emit)this.emit('Annotation cancelled');}
  clear(){this.cancel(false);for(const e of this.entities)this.viewer.entities.remove(e);this.entities=[];this.lastRoute=[];this.emit('Annotations cleared');}
  drawBoundaryGeometry(geometry,label='BOUNDARY'){const groups=geometry?.type==='Polygon'?[geometry.coordinates]:geometry?.type==='MultiPolygon'?geometry.coordinates:[];if(!groups.length)return false;const C=window.Cesium;let first=[];for(const polygon of groups){const ring=thinRing(polygon?.[0]||[]);if(ring.length<3)continue;const positions=ring.map(([lon,lat])=>C.Cartesian3.fromDegrees(lon,lat,45));const e=this.viewer.entities.add({polygon:{hierarchy:new C.PolygonHierarchy(positions),material:C.Color.CYAN.withAlpha(.07),outline:true,outlineColor:C.Color.CYAN}});e.__snxAnnotation='boundary';this.entities.push(e);if(!first.length)first=ring;}if(!first.length)return false;const center={lon:first.reduce((s,p)=>s+p[0],0)/first.length,lat:first.reduce((s,p)=>s+p[1],0)/first.length};this.drawSummaryLabel(center,label.toUpperCase().slice(0,60));this.emit('Boundary resolved');return true;}
  loadRoute(points=[]){const pts=points.filter(p=>Number.isFinite(p?.lat)&&Number.isFinite(p?.lon)).slice(0,16);if(pts.length<2)return false;this.drawPolyline(pts,'route');for(const p of pts)this.drawVertex(p,true);this.lastRoute=pts;this.emit('Shared route restored');return true;}
  pick(position){const C=window.Cesium;const cart=this.viewer.camera.pickEllipsoid(position,this.viewer.scene.globe.ellipsoid);if(!cart)return null;const p=C.Cartographic.fromCartesian(cart);return {lon:C.Math.toDegrees(p.longitude),lat:C.Math.toDegrees(p.latitude),alt:0};}
  drawVertex(p,persistent=false){const C=window.Cesium;const e=this.viewer.entities.add({position:C.Cartesian3.fromDegrees(p.lon,p.lat,12),point:{pixelSize:8,color:C.Color.CYAN,outlineColor:C.Color.BLACK,outlineWidth:2}});(persistent?this.entities:this.draftVertices).push(e);}
  drawMark(p){const C=window.Cesium;const label=`MARK ${this.entities.filter(e=>e.__snxMark).length+1}`;const e=this.viewer.entities.add({position:C.Cartesian3.fromDegrees(p.lon,p.lat,18),point:{pixelSize:12,color:C.Color.CYAN,outlineColor:C.Color.BLACK,outlineWidth:2},label:{text:label,font:'11px monospace',fillColor:C.Color.CYAN,pixelOffset:new C.Cartesian2(0,-20),showBackground:true,backgroundColor:new C.Color(0,0,0,.68)}});e.__snxMark=true;this.entities.push(e);}
  updatePreview(){this.clearPreview();if(this.points.length<2)return;const C=window.Cesium;const positions=this.points.map(p=>C.Cartesian3.fromDegrees(p.lon,p.lat,60));const e=this.viewer.entities.add({polyline:{positions,width:2,material:C.Color.CYAN.withAlpha(.72),clampToGround:false}});this.preview.push(e);if(this.mode==='area'&&this.points.length>=3){const p=this.viewer.entities.add({polygon:{hierarchy:new C.PolygonHierarchy(positions),material:C.Color.CYAN.withAlpha(.08),outline:true,outlineColor:C.Color.CYAN}});this.preview.push(p);}}
  clearPreview(){for(const e of this.preview)this.viewer.entities.remove(e);this.preview=[];}
  drawPolyline(pts,kind){const C=window.Cesium;const e=this.viewer.entities.add({polyline:{positions:pts.map(p=>C.Cartesian3.fromDegrees(p.lon,p.lat,70)),width:kind==='measure'?3:4,material:kind==='measure'?C.Color.ORANGE:C.Color.CYAN}});e.__snxAnnotation=kind;this.entities.push(e);}
  drawPolygon(pts){const C=window.Cesium;const e=this.viewer.entities.add({polygon:{hierarchy:new C.PolygonHierarchy(pts.map(p=>C.Cartesian3.fromDegrees(p.lon,p.lat,20))),material:C.Color.CYAN.withAlpha(.12),outline:true,outlineColor:C.Color.CYAN}});e.__snxAnnotation='area';this.entities.push(e);}
  drawSummaryLabel(p,text){const C=window.Cesium;const e=this.viewer.entities.add({position:C.Cartesian3.fromDegrees(p.lon,p.lat,100),label:{text,font:'11px monospace',fillColor:C.Color.ORANGE,showBackground:true,backgroundColor:new C.Color(0,0,0,.74),pixelOffset:new C.Cartesian2(0,-12)}});this.entities.push(e);}
  emit(message){this.dispatchEvent(new CustomEvent('change',{detail:{mode:this.mode,points:this.points.length,message,lastRoute:this.lastRoute}}));}
}
function centroid(points){return {lat:points.reduce((s,p)=>s+p.lat,0)/points.length,lon:points.reduce((s,p)=>s+p.lon,0)/points.length,alt:0}}
function thinRing(ring){if(ring.length<=700)return ring;const step=Math.ceil(ring.length/700),out=[];for(let i=0;i<ring.length;i+=step)out.push(ring[i]);if(out.length&&out[0]!==out.at(-1))out.push(out[0]);return out}
