export class SceneDirector extends EventTarget{
  constructor(globe,annotations){super();this.globe=globe;this.viewer=globe.viewer;this.annotations=annotations;this.running=false;this.cancelToken=0;this.artifacts=[];}
  stop(notify=true){this.running=false;this.cancelToken++;try{this.viewer.camera.cancelFlight()}catch{}if(notify)this.emit('Scene stopped');}
  clearArtifacts(){for(const e of this.artifacts)this.viewer.entities.remove(e);this.artifacts=[];}
  async orbitSelected({duration=12,range=12000}={}){const target=this.globe.selected?.entity;if(!target){this.emit('Select a contact first');return false;}this.stop(false);this.running=true;const token=++this.cancelToken,C=window.Cesium,start=performance.now();this.globe.stopFollow();return await new Promise(resolve=>{const frame=now=>{if(!this.running||token!==this.cancelToken){resolve(false);return;}let pos;try{pos=target.position?.getValue?.(this.viewer.clock.currentTime)||target.position}catch{pos=null}if(!pos){this.stop();resolve(false);return;}const t=(now-start)/(duration*1000);if(t>=1){this.viewer.camera.lookAtTransform(C.Matrix4.IDENTITY);this.running=false;this.emit('Orbit complete');resolve(true);return;}this.viewer.camera.lookAt(pos,new C.HeadingPitchRange(t*Math.PI*2,C.Math.toRadians(-25),range));requestAnimationFrame(frame)};requestAnimationFrame(frame)});}
  async worldSweep(){this.stop(false);this.globe.stopFollow();this.running=true;const token=++this.cancelToken;const stops=[[-122.4,37.8,1700000],[-74,40.7,1500000],[2.35,48.85,1500000],[55.27,25.2,1700000],[116.4,39.9,1800000],[139.69,35.68,1500000],[151.2,-33.86,1700000]];for(const p of stops){if(!this.running||token!==this.cancelToken)return false;await this.fly(p,.9);}this.running=false;this.emit('World sweep complete');return true;}
  async playRoute(points=this.annotations.lastRoute){if(!points?.length){this.emit('Create a route annotation first');return false;}this.stop(false);this.globe.stopFollow();this.running=true;const token=++this.cancelToken;for(const p of points){if(!this.running||token!==this.cancelToken)return false;await this.fly([p.lon,p.lat,Math.max(180000,Math.min(800000,points.length*65000))],.8);}this.running=false;this.emit('Route scene complete');return true;}
  async launchReconstruction(meta=this.globe.selected?.meta){if(meta?.type!=='LAUNCH'||!Number.isFinite(meta.latitude)||!Number.isFinite(meta.longitude)){this.emit('Select a launch site first');return false;}this.stop(false);this.clearArtifacts();this.globe.stopFollow();const C=window.Cesium,lat=meta.latitude,lon=meta.longitude,cos=Math.max(.2,Math.cos(lat*Math.PI/180));const alts=[200,5000,22000,55000,110000,190000,310000,460000],points=alts.map((alt,i)=>({lon:lon+(i*i*.18)/cos,lat:lat+i*.055,alt}));const positions=points.map(p=>C.Cartesian3.fromDegrees(p.lon,p.lat,p.alt));const line=this.viewer.entities.add({polyline:{positions,width:3,material:C.Color.MAGENTA.withAlpha(.75)},properties:{snxMeta:{type:'RECONSTRUCTED_TRAJECTORY',name:`${meta.name||'Launch'} reconstructed estimate`,source:'ShadowNex model',accuracy:'RECONSTRUCTED ESTIMATE — NOT LIVE TELEMETRY'}}});const label=this.viewer.entities.add({position:positions[Math.min(3,positions.length-1)],label:{text:'RECONSTRUCTED ESTIMATE',font:'10px monospace',fillColor:C.Color.MAGENTA,showBackground:true,backgroundColor:new C.Color(0,0,0,.74),pixelOffset:new C.Cartesian2(0,-15)}});this.artifacts.push(line,label);this.running=true;const token=++this.cancelToken;for(const p of points){if(!this.running||token!==this.cancelToken)return false;await this.fly([p.lon,p.lat,Math.max(90000,p.alt+120000)],.6);}this.running=false;this.emit('Launch reconstruction complete · estimate only');return true;}
  fly([lon,lat,alt],duration){return new Promise(resolve=>this.viewer.camera.flyTo({destination:window.Cesium.Cartesian3.fromDegrees(lon,lat,alt),duration:this.globe.settings.reduceMotion?0:duration,complete:resolve,cancel:resolve}));}
  emit(message){this.dispatchEvent(new CustomEvent('change',{detail:{running:this.running,message}}));}
}
