import { SourceRegistry } from './core/sourceRegistry.js';
import { loadSettings, saveSettings, resetSettings } from './core/settings.js';
import { GlobeController } from './globe/GlobeController.js';
import { AircraftLayer } from './layers/AircraftLayer.js';
import { EarthquakeLayer } from './layers/EarthquakeLayer.js';
import { FireLayer } from './layers/FireLayer.js';
import { SatelliteLayer } from './layers/SatelliteLayer.js';
import { LaunchLayer } from './layers/LaunchLayer.js';
import { ContextLayer } from './layers/ContextLayer.js';
import { RadioLayer } from './layers/RadioLayer.js';
import { CctvLayer } from './layers/CctvLayer.js';
import { BikeLayer } from './layers/BikeLayer.js';
import { VesselLayer } from './layers/VesselLayer.js';
import { SubseaLayer } from './layers/SubseaLayer.js';
import { CommandEngine } from './core/commandEngine.js';
import { drawAppQr } from './core/qr.js';
import { escapeHtml, fmtAlt, fmtNum } from './core/geo.js';
import { correlateContacts } from './core/contactCorrelation.js';

export class ShadowNexPrime {
 constructor(){this.version='2.2.0';this.settings=loadSettings();this.registry=new SourceRegistry();this.layers=new Map();this.command=new CommandEngine(this);this.audio=new Audio();this.audio.crossOrigin='anonymous';}
 async init(){
   this.applyMotion(); this.globe=new GlobeController('globe',this.settings); await this.globe.init();
   [new AircraftLayer(this),new EarthquakeLayer(this),new FireLayer(this),new SatelliteLayer(this),new LaunchLayer(this),new ContextLayer(this),new RadioLayer(this),new CctvLayer(this),new BikeLayer(this),new VesselLayer(this),new SubseaLayer(this)].forEach(l=>this.layers.set(l.id,l));
   this.registry.define('traffic','Traffic','TomTom'); this.registry.set('traffic',{status:this.settings.tomtomKey?'STANDBY':'STANDBY',note:this.settings.tomtomKey?'Layer disabled':'Add TomTom key in Settings'});
   this.bindUi(); this.renderLayers(); this.renderPulse(); this.updateDiagnostics(); this.setLens(this.settings.lens||'normal',false); this.applyUrlState();
   this.globe.addEventListener('select',e=>this.renderScope(e.detail)); this.registry.addEventListener('change',()=>{this.renderPulse();this.updateDiagnostics();});
   this.globe.annotation.addEventListener('change',e=>{const d=e.detail||{};this.$('annotationStatus').textContent=d.mode?`${String(d.mode).toUpperCase()} · ${d.points} POINTS`:d.message||'READY';if(d.message)this.toast(d.message);});
   this.globe.sceneDirector.addEventListener('change',e=>{if(e.detail?.message)this.toast(e.detail.message);});
   this.globe.addEventListener('follow',e=>this.updateFollowUi(e.detail));
   this.clockTimer=setInterval(()=>this.tickClock(),1000);this.cockpitTimer=setInterval(()=>this.updateCockpitHud(),250);this.tickClock();
   await this.setLayer('earthquakes',true); await this.setLayer('aircraft',true);
   window.__shadowNexPrime=this; return this;
 }
 densityLimit(low,normal,high){return this.settings.markerDensity==='low'?low:this.settings.markerDensity==='high'?high:normal;}
 bindUi(){
   const $=id=>document.getElementById(id);this.$=$;
   $('menuBtn').onclick=()=>$('layerPanel').classList.toggle('open'); $('scopePanel').onclick=e=>{if(e.target===$('scopePanel')||e.target.closest('.panel-title'))$('scopePanel').classList.toggle('expanded');};
   $('settingsBtn').onclick=()=>this.openSettings(); $('shareBtn').onclick=()=>this.share(); $('commandBtn').onclick=()=>$('commandDialog').showModal();
   $('pulseToggle').onclick=()=>$('pulseTray').classList.toggle('collapsed'); $('markBtn').onclick=()=>this.globe.armAnnotation('mark'); $('routeBtn').onclick=()=>this.globe.armAnnotation('route'); $('areaBtn').onclick=()=>this.globe.armAnnotation('area'); $('measureBtn').onclick=()=>this.globe.armAnnotation('measure'); $('finishAnnoBtn').onclick=()=>this.globe.finishAnnotation(); $('clearMarksBtn').onclick=()=>this.globe.clearAnnotations();
   $('orbitSceneBtn').onclick=()=>this.globe.sceneDirector.orbitSelected(); $('worldSceneBtn').onclick=()=>this.globe.sceneDirector.worldSweep(); $('routeSceneBtn').onclick=()=>this.globe.sceneDirector.playRoute(); $('stopSceneBtn').onclick=()=>this.globe.sceneDirector.stop();
   $('trackBtn').onclick=()=>{const on=!this.globe.tracking;on?this.globe.setTracking(true):this.globe.stopFollow();$('trackBtn').textContent=on?'RELEASE':'TRACK';};
   $('cockpitBtn').onclick=()=>{const on=!this.globe.cockpit;on?this.globe.setCockpit(true):this.globe.stopFollow();$('cockpitBtn').textContent=on?'EXIT COCKPIT':'COCKPIT';};
   document.querySelectorAll('[data-lens]').forEach(b=>b.onclick=()=>this.setLens(b.dataset.lens));
   $('saveSettingsBtn').onclick=e=>{e.preventDefault();this.settings={...this.settings,cesiumToken:$('cesiumToken').value.trim(),tomtomKey:$('tomtomKey').value.trim(),aisKey:$('aisKey').value.trim(),reduceMotion:$('reduceMotion').checked,markerDensity:$('markerDensity').value};saveSettings(this.settings);this.applyMotion();$('settingsDialog').close();this.toast('Settings saved. Reload to apply a new Cesium token.');this.renderLayers();};
   $('resetSettingsBtn').onclick=()=>{this.settings=resetSettings();this.applyMotion();this.openSettings();this.toast('Local ShadowNex settings reset.');};
   $('copyLinkBtn').onclick=async()=>{await navigator.clipboard?.writeText(this.shareUrl());this.toast('Share link copied.');};
   $('runCommandBtn').onclick=()=>this.runCommand(); $('commandInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();this.runCommand();}}); $('micBtn').onclick=()=>this.listen();
 }
 renderLayers(){const list=this.$('layerList');list.innerHTML='';const defs=[...this.layers.values()].map(l=>({id:l.id,label:l.label,description:l.description,active:l.enabled}));defs.push({id:'traffic',label:'Traffic',description:'TomTom flow tiles',active:!!this.globe.trafficLayer});for(const d of defs){const b=document.createElement('button');b.className='layer-btn'+(d.active?' active':'');b.innerHTML=`<span><b>${escapeHtml(d.label)}</b><small>${escapeHtml(d.description)}</small></span><i class="lamp"></i>`;b.onclick=()=>this.setLayer(d.id,!d.active);list.appendChild(b);}}
 async setLayer(id,on){if(id==='traffic'){if(on&&!this.settings.tomtomKey){this.toast('Add a TomTom key in Settings first.');this.registry.set('traffic',{status:'STANDBY',note:'TomTom key required'});return;}this.globe.setTraffic(this.settings.tomtomKey,on);this.registry.set('traffic',{status:on?'LIVE':'STANDBY',count:on?1:0,updatedAt:on?Date.now():null,note:on?'TomTom flow tiles':'Layer disabled'});this.renderLayers();return;}
   const l=this.layers.get(id);if(!l)return;on?await l.enable():l.disable();this.renderLayers();}
 setLens(name,persist=true){const app=document.getElementById('app');for(const n of ['normal','nvg','thermal','crt'])app.classList.remove(`lens-${n}`);app.classList.add(`lens-${name}`);document.querySelectorAll('[data-lens]').forEach(b=>b.classList.toggle('active',b.dataset.lens===name));this.settings.lens=name;if(persist)saveSettings(this.settings);}
 applyMotion(){document.documentElement.classList.toggle('reduce-motion',!!this.settings.reduceMotion);}
 renderPulse(){const all=this.registry.all();this.$('pulseSummary').textContent=this.registry.summary();this.$('pulseGrid').innerHTML=all.map(x=>`<div class="pulse-card"><b>${escapeHtml(x.label)}</b><span class="status-${x.status.toLowerCase()}">${x.status}</span><small>${x.count?` · ${x.count}`:''}</small></div>`).join('');}
 renderScope(meta){const empty=this.$('scopeEmpty'),box=this.$('scopeContent'),actions=this.$('scopeActions');if(!meta){empty.classList.remove('hidden');box.classList.add('hidden');actions.classList.add('hidden');return;}empty.classList.add('hidden');box.classList.remove('hidden');actions.classList.remove('hidden');const rows=[];const skip=new Set(['name','type','url','stream']);for(const [k,v] of Object.entries(meta)){if(skip.has(k)||v==null||v==='')continue;let value=v;if(k==='altitude')value=fmtAlt(Number(v));else if(typeof v==='number')value=fmtNum(v,2);else value=String(v);rows.push(`<div class="scope-row"><span>${escapeHtml(k.replace(/[A-Z]/g,m=>' '+m).toUpperCase())}</span><span>${escapeHtml(value)}</span></div>`);}box.innerHTML=`<div class="scope-name">${escapeHtml(meta.name||meta.type||'CONTACT')}</div><div class="scope-row"><span>TYPE</span><span>${escapeHtml(meta.type||'CONTACT')}</span></div>${rows.join('')}`;
   if(meta.type==='RADIO'&&meta.stream){const play=document.createElement('button');play.className='hud-btn wide';play.textContent='PLAY RADIO';play.onclick=()=>{this.audio.src=meta.stream;this.audio.play().then(()=>this.toast(`Playing ${meta.name}`)).catch(()=>this.toast('Radio stream could not be played.'));};box.appendChild(play);}if(meta.url){const open=document.createElement('button');open.className='ghost-btn wide';open.textContent='OPEN SOURCE';open.onclick=()=>window.open(meta.url,'_blank','noopener');box.appendChild(open);}if(meta.type==='LAUNCH'){const recon=document.createElement('button');recon.className='hud-btn wide';recon.textContent='RECONSTRUCT LAUNCH';recon.onclick=e=>{e.stopPropagation();this.globe.sceneDirector.launchReconstruction(meta);};box.appendChild(recon);}const nearby=correlateContacts(meta,[...this.layers.values()],{radiusKm:250,limit:8});if(nearby.length){const wrap=document.createElement('div');wrap.className='correlation-box';const title=document.createElement('b');title.textContent=`PRIMECORRELATE™ · ${nearby.length} NEARBY`;wrap.appendChild(title);for(const x of nearby){const row=document.createElement('button');row.className='correlation-row';row.innerHTML=`<div><strong>${escapeHtml(x.meta.name||x.meta.type||'CONTACT')}</strong><small>${escapeHtml(x.relation)} · ${escapeHtml(x.meta.type||'CONTACT')}</small></div><span>${x.distanceKm.toFixed(1)} KM</span>`;row.onclick=e=>{e.stopPropagation();this.globe.select(x.meta,x.entity);if(Number.isFinite(x.meta.longitude)&&Number.isFinite(x.meta.latitude))this.globe.flyTo(x.meta.longitude,x.meta.latitude,Math.max(120000,Number(x.meta.altitude)||250000));};wrap.appendChild(row);}box.appendChild(wrap);}}
 tickClock(){this.$('utcClock').textContent=new Date().toISOString().slice(11,19)+' UTC';}
 updateFollowUi(detail={}){const on=!!detail.tracking,cockpit=!!detail.cockpit;this.$('trackBtn').textContent=on?'RELEASE':'TRACK';this.$('cockpitBtn').textContent=cockpit?'EXIT COCKPIT':'COCKPIT';document.getElementById('app').classList.toggle('cockpit-mode',cockpit);this.$('cockpitOverlay').classList.toggle('hidden',!cockpit);this.$('cockpitOverlay').setAttribute('aria-hidden',cockpit?'false':'true');}
 updateCockpitHud(){if(!this.globe?.cockpit||!this.globe.selected?.meta||!this.$)return;const m=this.globe.selected.meta,heading=Number(m.heading),speed=Number(m.velocity??m.speed),alt=Number(m.altitude);this.$('cockpitTarget').textContent=String(m.name||m.type||'CONTACT').slice(0,24);this.$('cockpitCohort').textContent=String(m.cohort||m.type||'CONTACT').slice(0,32);this.$('cockpitHeading').textContent=Number.isFinite(heading)?`${String(Math.round((heading%360+360)%360)).padStart(3,'0')}°`:'---°';const spd=Number.isFinite(speed)?(m.type==='AIRCRAFT'?`${Math.round(speed*1.94384)} KT`:`${speed.toFixed(1)} KT`):'—';this.$('cockpitSpeed').textContent=`SPD ${spd}`;this.$('cockpitAltitude').textContent=fmtAlt(alt);this.$('cockpitSource').textContent=String(m.source||'PUBLIC SOURCE').toUpperCase().slice(0,28);}
 toast(msg){const t=this.$('toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(this.toastTimer);this.toastTimer=setTimeout(()=>t.classList.add('hidden'),2600);}
 openSettings(){this.$('cesiumToken').value=this.settings.cesiumToken||'';this.$('tomtomKey').value=this.settings.tomtomKey||'';this.$('aisKey').value=this.settings.aisKey||'';this.$('reduceMotion').checked=!!this.settings.reduceMotion;this.$('markerDensity').value=this.settings.markerDensity||'normal';this.updateDiagnostics();if(!this.$('settingsDialog').open)this.$('settingsDialog').showModal();}
 updateDiagnostics(){if(!this.$)return;const live=this.registry.all().filter(x=>x.status==='LIVE').length;const C=window.Cesium;this.$('diagnostics').innerHTML=`<span>Version: v${this.version}</span><span>Node target: 22.x</span><span>WebGL: ${C&&this.globe?.viewer?'READY':'CHECKING'}</span><span>Network: ${navigator.onLine?'ONLINE':'OFFLINE'}</span><span>NexPulse live feeds: ${live}</span><span>OpenAI briefing: SERVER ENV REQUIRED</span>`;}
 shareUrl(){const s=this.globe.state();const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('snx','2');u.searchParams.set('p',[s.lat.toFixed(4),s.lon.toFixed(4),Math.round(s.alt)].join(','));const active=[...this.layers.values()].filter(l=>l.enabled).map(l=>l.id);if(this.globe.trafficLayer)active.push('traffic');u.searchParams.set('l',active.join('.'));u.searchParams.set('v',this.settings.lens||'normal');const route=this.globe.annotation?.lastRoute||[];if(route.length>1)u.searchParams.set('r',route.slice(0,16).map(p=>`${p.lon.toFixed(4)},${p.lat.toFixed(4)}`).join('|'));return u.toString();}
 async share(){const url=this.shareUrl();if(navigator.share){try{await navigator.share({title:'ShadowNex Prime™',text:'Global Situational Intelligence',url});return;}catch(e){if(e?.name==='AbortError')return;}}this.$('shareLink').textContent=url;try{drawAppQr(this.$('qrCanvas'),url,'SNX');}catch{const c=this.$('qrCanvas'),ctx=c.getContext('2d');ctx.fillStyle='#071117';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#00f0ff';ctx.textAlign='center';ctx.fillText('SNX',c.width/2,c.height/2);}this.$('shareDialog').showModal();}
 async runCommand(){const input=this.$('commandInput'),raw=input.value.trim();if(!raw)return;this.logCommand(raw,'user');input.value='';const response=await this.command.run(raw);this.logCommand(response,'system');}
 logCommand(text,role){const p=document.createElement('p');p.className=role;p.textContent=(role==='user'?'> ':'SNX: ')+text;this.$('commandLog').appendChild(p);this.$('commandLog').scrollTop=this.$('commandLog').scrollHeight;}
 listen(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){this.toast('Speech recognition is not available in this browser.');return;}const rec=new R();rec.lang='en-US';rec.interimResults=false;rec.onresult=e=>{this.$('commandInput').value=e.results[0][0].transcript;this.runCommand();};rec.onerror=()=>this.toast('Voice recognition failed.');rec.start();}
 findNearestContact({type=null,militaryOnly=false,radiusKm=3000}={}){const originMeta=this.globe.selected?.meta||(()=>{const p=this.globe.focusCoordinates();return {type:'ORIGIN',id:'focus',latitude:p.lat,longitude:p.lon,name:'VIEW CENTER'}})();let hits=correlateContacts(originMeta,[...this.layers.values()],{radiusKm,limit:200});if(type)hits=hits.filter(x=>x.meta.type===type);if(militaryOnly)hits=hits.filter(x=>x.meta.type==='AIRCRAFT'&&x.meta.militaryLikely);const hit=hits[0];if(!hit)return null;this.globe.select(hit.meta,hit.entity);this.globe.flyTo(hit.meta.longitude,hit.meta.latitude,Math.max(120000,Number(hit.meta.altitude)||250000));return hit;}
 async outlineBoundary(name){this.toast(`Resolving ${name}…`);try{const r=await fetch(`/api/boundary?q=${encodeURIComponent(name)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);const ok=this.globe.annotation.drawBoundaryGeometry(d.geometry,d.name||name);if(!ok)throw new Error('Unsupported boundary geometry');if(Array.isArray(d.bbox)&&d.bbox.length===4){const [west,south,east,north]=d.bbox.map(Number),lon=(west+east)/2,lat=(south+north)/2,span=Math.max(Math.abs(east-west),Math.abs(north-south));this.globe.flyTo(lon,lat,Math.max(250000,span*150000));}return `Outlined ${d.name||name} from OpenStreetMap.`;}catch(e){return `Boundary unavailable: ${e.message}.`;}}
 async requestBriefing(userPrompt='Brief me'){const snapshot={camera:this.globe.state(),selected:this.globe.selected?.meta||null,sources:this.registry.all().map(x=>({id:x.id,status:x.status,count:x.count,note:x.note})),activeLayers:[...this.layers.values()].filter(l=>l.enabled).map(l=>l.id),lens:this.settings.lens,annotationRoute:this.globe.annotation?.lastRoute||[],nearby:this.globe.selected?.meta?correlateContacts(this.globe.selected.meta,[...this.layers.values()],{radiusKm:250,limit:8}).map(x=>({name:x.meta.name,type:x.meta.type,distanceKm:Number(x.distanceKm.toFixed(1)),relation:x.relation})):[]};try{const r=await fetch('/api/briefing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:userPrompt,snapshot})});const d=await r.json();if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d.text||'No briefing returned.';}catch(e){return `AI briefing unavailable: ${e.message}. Live source status: ${this.registry.summary()}.`;}}
 applyUrlState(){const p=new URLSearchParams(location.search);if(p.get('snx')!=='2')return;const pos=p.get('p')?.split(',').map(Number);if(pos?.length===3&&pos.every(Number.isFinite))setTimeout(()=>this.globe.flyTo(pos[1],pos[0],pos[2]),200);const lens=p.get('v');if(['normal','nvg','thermal','crt'].includes(lens))this.setLens(lens,false);const layers=p.get('l')?.split('.').filter(Boolean)||[];setTimeout(()=>layers.forEach(id=>this.setLayer(id,true)),500);const route=(p.get('r')||'').split('|').map(x=>x.split(',').map(Number)).filter(x=>x.length===2&&x.every(Number.isFinite)).map(([lon,lat])=>({lon,lat,alt:0}));if(route.length>1)setTimeout(()=>this.globe.annotation.loadRoute(route),650);}
}
