const CACHE={at:0,data:null},TTL=5*60*1000;
export default async function handler(req,res){
  if(CACHE.data&&Date.now()-CACHE.at<TTL)return res.status(200).json({...CACHE.data,cached:true});
  const defs=[['OKTraffic / Oklahoma',loadOklahoma],['Transport for London',loadTfl],['Caltrans',loadCaltrans],['City of Austin',loadAustin],['Seattle DOT',loadSeattle],['Maryland CHART',loadMaryland]];
  const jobs=await Promise.allSettled(defs.map(([,fn])=>fn())),points=[],sources=[];
  jobs.forEach((job,i)=>{const name=defs[i][0];if(job.status==='fulfilled'){points.push(...job.value.points);sources.push({name,count:job.value.points.length,status:'LIVE'});}else sources.push({name,count:0,status:'DEGRADED',error:job.reason?.message||String(job.reason)});});
  const data={points,sources,updatedAt:Date.now(),coverage:['Oklahoma City / Tulsa / Oklahoma highways','California statewide','London','Austin','Seattle','Maryland / DC region'],regions:[{id:'okc',name:'Oklahoma City',provider:'OKTraffic / Oklahoma',lat:35.4676,lon:-97.5164,alt:180000},{id:'tulsa',name:'Tulsa',provider:'OKTraffic / Oklahoma',lat:36.154,lon:-95.993,alt:180000},{id:'california',name:'California',provider:'Caltrans',lat:36.7783,lon:-119.4179,alt:1400000},{id:'london',name:'London',provider:'Transport for London',lat:51.5074,lon:-0.1278,alt:160000},{id:'austin',name:'Austin',provider:'City of Austin',lat:30.2672,lon:-97.7431,alt:160000},{id:'seattle',name:'Seattle',provider:'Seattle DOT',lat:47.6062,lon:-122.3321,alt:160000},{id:'maryland',name:'Maryland / DC region',provider:'Maryland CHART',lat:39.0458,lon:-76.6413,alt:420000}]};CACHE.at=Date.now();CACHE.data=data;return res.status(200).json(data);
}
async function loadOklahoma(){
  const filter=JSON.stringify({include:[{relation:'mapCameras',scope:{include:'streamDictionary',where:{status:{neq:'Out Of Service'},type:'Web',blockAtis:{neq:'1'}}}}]});
  const r=await fetch('https://oktraffic.org/api/CameraPoles',{headers:{Accept:'application/json','Content-Type':'application/json',Referer:'https://oktraffic.org/','User-Agent':'ShadowNexPrime/2.2.1 (CactusByte Studios)',filter}});
  if(!r.ok)throw new Error(`OKTraffic HTTP ${r.status}`);
  const poles=await r.json(),points=[];
  for(const pole of Array.isArray(poles)?poles:[])for(const cam of pole.mapCameras||[]){const sd=cam.streamDictionary||{},lat=Number(cam.latitude),lon=Number(cam.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;points.push({id:`OK-${cam.id}`,name:cam.location||sd.streamName||pole.name||'Oklahoma Traffic Camera',lat,lon,status:cam.status||'LIVE',direction:cam.direction||null,url:'https://oktraffic.org/',streamUrl:sd.streamSrc||null,source:'OKTraffic / ODOT-OTA'});}
  return {points};
}
async function loadTfl(){const d=await json('https://api.tfl.gov.uk/Place/Type/JamCam'),points=[];for(const c of Array.isArray(d)?d:[]){const lat=Number(c.lat),lon=Number(c.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const p=Object.fromEntries((c.additionalProperties||[]).map(x=>[x.key,x.value]));points.push({id:c.id,name:c.commonName||'London JamCam',lat,lon,status:p.available,direction:p.view,url:p.videoUrl||p.imageUrl||null,previewUrl:p.imageUrl||null,source:'Transport for London'});}return {points};}
async function loadCaltrans(){const base='https://caltrans-gis.dot.ca.gov/arcgis/rest/services/chhighway/CCTV/FeatureServer/0/query',points=[],pageSize=2000;for(let offset=0;offset<12000;offset+=pageSize){const u=new URL(base);u.searchParams.set('where','1=1');u.searchParams.set('outFields','OBJECTID,locationName,nearbyPlace,longitude,latitude,direction,inService,currentImageURL,streamingVideoURL,county,route');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','4326');u.searchParams.set('f','geojson');u.searchParams.set('resultRecordCount',String(pageSize));u.searchParams.set('resultOffset',String(offset));const d=await json(u),features=d.features||[];for(const f of features){const p=f.properties||{},coords=f.geometry?.coordinates||[],lon=Number(p.longitude??coords[0]),lat=Number(p.latitude??coords[1]);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;points.push({id:`CA-${p.OBJECTID}`,name:p.locationName||p.nearbyPlace||'Caltrans CCTV',lat,lon,status:p.inService,direction:p.direction,url:p.streamingVideoURL||p.currentImageURL||null,previewUrl:p.currentImageURL||null,source:'Caltrans',county:p.county,route:p.route});}if(features.length<pageSize)break;}return {points};}
async function loadAustin(){const d=await json('https://data.austintexas.gov/api/v3/views/b4k4-adkb/query.geojson?accessType=DOWNLOAD'),points=[];for(const f of d.features||[]){const p=f.properties||{},coords=f.geometry?.coordinates||[],lon=Number(coords[0]??p.longitude),lat=Number(coords[1]??p.latitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const id=p.camera_id??p.cameraid??p.id??f.id??points.length;points.push({id:`ATX-${id}`,name:p.location_name??p.locationname??p.location??p.name??`Austin Camera ${id}`,lat,lon,status:p.camera_status??p.status??null,direction:p.direction??null,url:p.url??p.camera_url??null,previewUrl:p.image_url??p.snapshot_url??null,source:'City of Austin'});}return {points};}
async function loadSeattle(){const u=new URL('https://services.arcgis.com/ZOyb2t4B0UYuYNYH/arcgis/rest/services/Traffic_Cameras_CDL/FeatureServer/0/query');u.searchParams.set('where','1=1');u.searchParams.set('outFields','OBJECTID,NAME,URL,LOCATION,SERVSTAT,STREAM_NAME,DISTRICT');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','4326');u.searchParams.set('f','geojson');const d=await json(u),points=[];for(const f of d.features||[]){const p=f.properties||{},coords=f.geometry?.coordinates||[],lon=Number(coords[0]),lat=Number(coords[1]);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;points.push({id:`SEA-${p.OBJECTID}`,name:p.NAME||p.LOCATION||'Seattle Traffic Camera',lat,lon,status:p.SERVSTAT,url:p.URL||null,source:'Seattle DOT',district:p.DISTRICT});}return {points};}
async function loadMaryland(){const u=new URL('https://mdgeodata.md.gov/imap/rest/services/Transportation/MD_TrafficCameras/FeatureServer/0/query');u.searchParams.set('where','1=1');u.searchParams.set('outFields','OBJECTID,location,county,feedID,url,lat,long');u.searchParams.set('returnGeometry','true');u.searchParams.set('outSR','4326');u.searchParams.set('f','geojson');u.searchParams.set('resultRecordCount','550');const d=await json(u),points=[];for(const f of d.features||[]){const p=f.properties||{},coords=f.geometry?.coordinates||[],lon=Number(p.long??coords[0]),lat=Number(p.lat??coords[1]);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;points.push({id:`MD-${p.OBJECTID}`,name:p.location||'Maryland Traffic Camera',lat,lon,status:'LIVE',url:p.url||null,source:'Maryland CHART',county:p.county,feedId:p.feedID});}return {points};}
async function json(url){const r=await fetch(url,{headers:{Accept:'application/json,application/geo+json','User-Agent':'ShadowNexPrime/2.2.1 (CactusByte Studios)'}});if(!r.ok)throw new Error(`${new URL(url).hostname} HTTP ${r.status}`);return await r.json();}
