const CACHE=new Map(),TTL=6*60*60*1000;
export default async function handler(req,res){
  if(req.method&&req.method!=='GET')return res.status(405).json({error:'GET required'});
  const u=new URL(req.url,'http://localhost'),type=(u.searchParams.get('type')||'').toLowerCase(),id=(u.searchParams.get('id')||'').trim(),name=(u.searchParams.get('name')||'').trim(),callsign=(u.searchParams.get('callsign')||'').trim(),key=[type,id,name,callsign].join('|').toLowerCase(),cached=CACHE.get(key);
  if(cached&&Date.now()-cached.at<TTL)return res.status(200).json({...cached.data,cached:true});
  try{let data;if(type==='aircraft')data=await enrichAircraft(id,callsign);else if(type==='satellite')data=await enrichSatellite(name);else return res.status(400).json({error:'Supported types: aircraft, satellite'});CACHE.set(key,{at:Date.now(),data});return res.status(200).json(data);}catch(e){return res.status(200).json({available:false,type,error:e?.message||String(e)});}
}
async function enrichAircraft(hex,callsign){if(!/^[a-f0-9]{6}$/i.test(hex))return {available:false,type:'aircraft',reason:'No valid Mode-S hex available'};const a=await safeJson(`https://hexdb.io/api/v1/aircraft/${encodeURIComponent(hex)}`),aircraft=a&&!a.error&&!a.status?{manufacturer:a.Manufacturer||null,type:a.Type||null,icaoType:a.ICAOTypeCode||null,registration:a.Registration||null,owner:a.RegisteredOwners||null,operatorCode:a.OperatorFlagCode||null}:null;let route=null;if(callsign){const rr=await safeJson(`https://hexdb.io/api/v1/route/icao/${encodeURIComponent(callsign)}`);if(rr?.route&&!rr.error){const [oc,dc]=String(rr.route).split('-'),[origin,destination]=await Promise.all([airport(oc),airport(dc)]);route={callsign:rr.flight||callsign,origin,destination,raw:rr.route,updatedAt:rr.updatetime?Number(rr.updatetime)*1000:null};}}return {available:!!aircraft||!!route,type:'aircraft',aircraft,route,photo:`https://hexdb.io/hex-image?hex=${encodeURIComponent(hex)}`,photoThumbnail:`https://hexdb.io/hex-image-thumb?hex=${encodeURIComponent(hex)}`,purpose:route?'Published route match from public aviation reference data. Specific mission or onboard purpose is not publicly identified.':'Specific mission, origin, and destination are not available from the current public reference data.',source:'HexDB'};}
async function airport(code){if(!code)return null;const d=await safeJson(`https://hexdb.io/api/v1/airport/icao/${encodeURIComponent(code)}`);if(!d||d.error||d.status)return {icao:code};return {icao:d.icao||code,iata:d.iata||null,name:d.airport||null,region:d.region_name||null,country:d.country_code||null};}
async function enrichSatellite(name){if(!name)return {available:false,type:'satellite'};const q=wikiQuery(name),search=await safeJson(`https://en.wikipedia.org/w/rest.php/v1/search/page?q=${encodeURIComponent(q)}&limit=1`),page=search?.pages?.[0];if(!page?.key&&!page?.title)return {available:false,type:'satellite',reason:'No English Wikipedia match'};const title=page.key||page.title,summary=await safeJson(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(title)}`);if(!summary)return {available:false,type:'satellite'};return {available:true,type:'satellite',title:summary.title||page.title,description:summary.description||page.description||null,summary:summary.extract||null,photo:summary.originalimage?.source||summary.thumbnail?.source||page.thumbnail?.url||null,photoThumbnail:summary.thumbnail?.source||page.thumbnail?.url||null,url:summary.content_urls?.desktop?.page||null,language:'en',source:'English Wikipedia / Wikimedia'};}
function wikiQuery(name){const n=String(name).trim();if(/^STARLINK[- ]/i.test(n))return 'Starlink';if(/^ONEWEB[- ]/i.test(n))return 'OneWeb satellite constellation';if(/^GPS /i.test(n)||/^NAVSTAR/i.test(n))return 'Global Positioning System satellite';if(/^IRIDIUM/i.test(n))return 'Iridium satellite constellation';if(/^(ISS|ZARYA)/i.test(n))return 'International Space Station';return n.replace(/\([^)]*\)/g,'').trim();}
async function safeJson(url){try{const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'ShadowNexPrime/2.2.1 (CactusByte Studios)'}});if(!r.ok)return null;return await r.json();}catch{return null}}
